### ISSUE TITLE
create AC tool to display all duplicate IPs in PDB

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#97] opened 2016-12-08 14:27 UTC
To help resolve the fallout of #70 - a tool that gives a current overview of all duplicate IPs in PDB would be helpful. That way we can go over them one by one and resolve them.

The tool should link the various fields to the pages related to such fields, so an admin can for instance delete an entry with just 1 or 2 mouse clicks

**Comment by vegu** [comment] 2016-12-08 14:32
duplicate of #96

**Closed by vegu** 2016-12-08 14:32 UTC
Labels: AC
