### ISSUE TITLE
queries by inactive users, which result in HTTP result 401, take too long to process, potentially burning CPU

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#1011] opened 2021-07-25 04:13 UTC
**Describe the bug**
I emailed 20C about this on 7/14.  Turning into an issue so it isn't lost.

I noticed that when a user's "is_active" status is set to false, queries will result in HTTP response code 401 (unauthorized) as expected, but a fair amount of CPU time is consumed, IIRC.  This means that disabling an hostile user to protect the service will not actually protect the service, because a DoS attack (sans rate limiting - #427 & #853) will still be possible.

**To Reproduce**
1. Login as test user.
2. In another browser on an admin account: disable test user by unchecking "is_active" in the control panel.
3. As the test user, perform a query, such as "GET /api/net?asn=6456".
4. Observe HTTP 401 result.  Repeat query a bunch.
5. Observe how queries still take a while to return 401 and how the system has to work hard to produce the result.

**Expected behavior**
"is_active" status, along with status such as admin status, should be cached locally within django, or something like that, even if the caching is only for 60 seconds.  Or at least cache when status is false/disabled.  Ie., a disabling should be quick/instant, while an enabling can take a minute or few.

**Who is affected by the problem?**
The community.

**What is the impact?**
Inability to effectively manage the shared resource.  Last time this happened, we had to use a network ACL to prevent abuse.

**Are there security concerns?**
Yes, DoS potential.

**Are there privacy concerns?**
Not that I can think of.

**What are the proposed actions?**
See above.

**What is the proposed priority?**
Seems important to me.  :-)

**Comment by arnoldnipper** [comment] 2021-07-25 10:35
+1

**Comment by arnoldnipper** [comment] 2021-07-25 10:36
@peeringdb/ac and @peeringdb/pc please support

**Comment by peterhelmenstine** [comment] 2021-07-31 18:54
+1

**Comment by DarwinCosta** [comment] 2021-08-11 16:40
+1

**Comment by vegu** [comment] 2022-03-30 17:17
@ccaputo not by design, but unsure where it changed - it's something we can ensure at the same place we ensure the changes for #1117 though

**Comment by leovegoda** [comment] 2023-07-26 15:38
@arnoldnipper Is is OK to move this to "Ready for Implementation" so I can schedule it?

**Comment by ccaputo** [comment] 2023-08-15 21:50
@leovegoda this is URGENTLY needed by Ops. Possibly a hot-fix. I am finding that when I disable an API key due to overloading, the requests continue to consume CPU time, apparently processing the request, even though HTTP 403 is being returned due to the disabled API key.

**Comment by martinhannigan** [comment] 2023-08-15 22:09
Hotfix for COGS makes sense to me. +1



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vegu** [comment] 2024-03-28 11:56
this was fixed in https://github.com/peeringdb/peeringdb/pull/1440/ but not linked in the PR, so was never closed

**Closed by vegu** 2024-03-28 11:56 UTC
Labels: bug

**Comment by peterhelmenstine** [comment] 2024-03-28 16:55
+1 for Chris efficiencies
