### ISSUE TITLE
Unable to add network 27330 via GUI

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#88] opened 2016-12-02 23:24 UTC
![20161202 peeringdb 03](https://cloud.githubusercontent.com/assets/16888757/20853793/c5653ea2-b8ee-11e6-88ea-1a4c44fe4143.png)

**Comment by vegu** [comment] 2016-12-03 08:36
There is a network with that ASN already so i suspect it might be blocking on that: https://www.peeringdb.com/net/11908 - need to look into why its not showing the error on the form correctly.

**Comment by arnoldnipper** [comment] 2016-12-03 14:58
Now it is as I have added it via the admin GUI. I've looked up that ASN in the DB with full view and it was not in the DB at all.

**Comment by vegu** [comment] 2016-12-03 15:10
I see - in that case, more information is required

- where you able to reproduce this on your end ? (or is that your screenshot?)
- could the user add other asns via the GUI ?
- browser info and complete form input would be helpful

**Comment by arnoldnipper** [comment] 2016-12-03 17:42
- This is my screenshot. I.e. I was able to reproduce what Greg Dendy reported. 

- Greg was not able to add other networks as well. I didn't try

- Google chrome Version 54.0.2840.99 m. What do you mean by "complete form input"? I only specified Name and ASN

**Comment by vegu** [comment] 2016-12-03 17:52
Able to reproduce and looking into this now

**Comment by vegu** [comment] 2016-12-03 18:11
fixed in 0fdfd05, also hot-fixed it on prod since it was a simple html error

**Closed** 2016-12-11 04:59 UTC
Labels: AC, bug
