### ISSUE TITLE
IXF-Importer: improved handling of how contacts are joined into direct conflict resolution deskpro tickets

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#875] opened 2020-11-11 08:50 UTC
**Issue**

Currently when the need for a direct conflict resolution arises, a Deskpro ticket is created and emails are dispatched to points of contact for the involved networks and exchanges. The ticket reference number is included in the subject as a means to route responses to these emails to the correct ticket on the Deskpro end.

So far on production this approach has turned out to be unreliable and responses have been seen to open new tickets instead of being routed into the existing ticket. 

**Proposal**

The Deskpro API endpoint for ticket creation has a `cc` parameter that allows us to specify additional addresses to be added to the ticket directly. We have reached out to their support and confirmed that Deskpro can then also be configured to automatically dispatch emails to those cc'd addresses and that those emails will have all the headers and reply ids set to make sure responses are routed to the correct ticket.

**Summary**

- Use Deskpro API's `cc` payload on ticket creation to directly cc additional contacts to the ticket
- Configure Deskpro event triggers to appropriately send emails to cc'd contacts during api ticket creation

**Comment by arnoldnipper** [comment] 2020-11-11 11:29
Identified as a bug and hence routed through to 3a, @peeringdb/pc

**Comment by ccaputo** [comment] 2020-11-20 21:08
Additional aspect to be included: Based on "IX-F Member Export URL Visibility" the Deskpro ticket created should only include the IX-F URL if visibility is set to "Public", since the email may go to parties other than the IX.  When public:

```
- IX-F Data: [URL]
```

When not public:

```
- IX-F Data: Not public
```

**Comment by ccaputo** [comment] 2021-01-14 03:48
Performed some testing of this.

I confirm the "IX-F Data:" privacy aspect of this has been tested and is working, so all good there.

I have also confirmed that client responses to the email they receive are working well, with respect to making it back to the intended ticket, while using a standard reply method.  Forwarding does not work in my testing, but regardless, this is a dramatic improvement.  (basically the subject line seems ignored, and headers present in a reply but not in a forward, make the difference)

I am seeing problem with respect to what data makes it to the client as compared to what is available in Deskpro.  For example, a client will receive only:

<img width="1006" alt="Screen Shot 2021-01-13 at 7 18 53 PM" src="https://user-images.githubusercontent.com/1417833/104541006-8d2f1480-55d5-11eb-9408-5bee3b6c5dad.png">

while the Deskpro view contains much more detail:

<img width="509" alt="Screen Shot 2021-01-13 at 7 18 40 PM" src="https://user-images.githubusercontent.com/1417833/104541031-9e782100-55d5-11eb-85fb-4161c103da1f.png">

Can we make it so the client also receives the data posted to the Deskpro ticket in the initial email they receive about the ticket, so they have an ability to understand what the ticket is actually about?

Also, I have noticed that in repeat testing of the same Importer issue, such as after a reset of IX-F Importer data on beta, there is a failure to allow a post to Deskpro, due to:

`{'status': 400, 'code': 'invalid_input', 'message': 'Request input is invalid.', 'errors': {'errors': [{'code': 'dupe_ticket', 'message': 'Duplicate ticket.'}]}}`

Please figure out the cause of the duplicate error and mitigate that.  I am guessing there needs to be something unique in the subject line.  I propose a datestamp-PID since the same conflict is unlikely to happen more than once per day, and certaily not with the same process ID of the running IX-F Importer.  Thus adding YYYYMMDD-PID to the end of the subject line, ala:

`[beta] [IX-F] SIX Seattle (Jumbo) AS6456 206.81.83.41 2001:504:16:1:0:297:0:1938 IX-F Conflict Resolution - 20210114-838`

and then of course testing to make sure this is sufficient to get Deskpro to not consider a new ticket to be a duplicate.

**Comment by ccaputo** [comment] 2021-01-14 18:16
CC: part of the above will soon be fixed by a Deskpro config change.

**Comment by ccaputo** [comment] 2021-01-14 23:30
The dup issue will be handled in another issue.

**Comment by ccaputo** [comment] 2021-01-20 21:25
Per @vegu (@peeringdb/20c), re-opening this per email discussions re Deskpro error involving trigger:

```
{'status': 500, 'code': 'error', 'message': '500 server error', 'errors': None}
```

**Comment by vegu** [comment] 2021-01-21 07:35
The current implementation of this feature causes the Deskpro API to error with a 500 internal error. Deskpro support was contacted and they are investigating the issue, which appears to be unique to the peeringdb deskpro account.

They have provided the following workaround:

- Use the deskpro api to manually create the person objects for the email addresses to  be cc'd on the ticket and then cc by person.id rather than email address.

**Comment by grizz** [comment] 2021-01-21 17:22
@peeringdb/pc @ccaputo 

Does this need to be updated before production release next week?

**Comment by ccaputo** [comment] 2021-01-21 17:26
> @peeringdb/pc @ccaputo
> 
> Does this need to be updated before production release next week?

I recommend no, in favor of a normal beta process subsequent to next week's production release.

**Comment by vegu** [comment] 2021-02-09 21:02
@ccaputo is this in a good state now?

**Comment by ccaputo** [comment] 2021-02-09 21:55
> @ccaputo is this in a good state now?

Yes, I think this issue can be closed.  If you are also okay with closing it, please do so.

**Closed** 2021-02-10 08:44 UTC
Labels: Minor, bug

**Comment by arnoldnipper** [comment] 2021-03-02 21:48
**Release Notes**
Internal issue. $subject says it all
