### ISSUE TITLE
Whois Output Error when querying huge records

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#51] opened 2016-08-17 22:41 UTC
When executing whois against our record, I’m getting most of the output, but
it dies in the facilities list: 

workingServ:~ mtindle$ whois -h whois.peeringdb.com AS6939

http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=12050

**Comment by job** [comment] 2016-11-22 09:15
Duplicate of #17

**Closed by job** 2016-11-22 09:15 UTC
Labels: bug
