### ISSUE TITLE
make all e-mails from PeeringDB DMARC compliant

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#100] opened 2016-12-14 23:54 UTC
Every now and then (e..g DeskPRO #1341) e-mails from PeeringDB can't be delivered interrupting communication with users

**Comment by job** [comment] 2017-07-06 15:45
@grizz no estimate yet

**Comment by grizz** [comment] 2017-11-05 17:35
Dupe of #174

**Closed by grizz** 2017-11-05 17:35 UTC
Labels: AC, bug, Minor
