### ISSUE TITLE
Add a clear error message, when user tries to re-add a previously deleted facility

### ISSUE THREAD

**Issue by tschmidt123** [peeringdb/peeringdb#580] opened 2019-09-26 12:08 UTC
Hi there,

after I deleted a Private Peering Location I´m not able to add this one again to my locations.

Thanks for your help!
Regards,
Thomas

**Comment by koalafil** [comment] 2019-10-02 12:57
@tschmidt123 could you pls send a mail to support@peeringdb.com? 
Our Admin Committee can look into your case then.

**Comment by tschmidt123** [comment] 2019-10-02 13:01
Hi all together.

That´s where I started (see attachment).

What should be my exact next step?

Thanks for your help!

Regards,
Thomas








Viele Grüße

Thomas Schmidt
Systems Engineer Network

[http://www.smart-infoscreen.de/pyur_signature_logo.png]

HL komm Telekommunikations GmbH
Nonnenmühlgasse 1
04107 Leipzig

E-Mail:

Thomas.Schmidt@pyur.com<mailto:Thomas.Schmidt@pyur.com>

Tel.:

+49-341-8697-148

Fax:

+49-341-8697-199


pyur.com/business<https://pyur.com/business>

Geschäftsführung: Erik Dähne, Richard Fahringer, Timm Degenhardt, Eike Walters
Sitz der Geschäftsführung: Nonnenmühlgasse 1, 04107 Leipzig
Amtsgericht Leipzig HRB-Nr. 13672

Zertifiziert nach:
ISO/IEC 27001:2013
ISO 9001:2015

Datenschutzhinweis:
Wir verarbeiten Ihre personenbezogenen Daten unter Beachtung der Bestimmungen der Datenschutz-Grundverordnung (DSGVO), des Bundesdatenschutzgesetzes (BDSG) sowie aller weiteren maßgeblichen Gesetze. Informationen über die Verarbeitung Ihrer personenbezogenen Daten durch uns und die Ihnen nach dem Datenschutzrecht zustehenden Rechte finden Sie in unserer Datenschutzerklärung unter pyur.com/business/datenschutz<https://www.pyur.com/business/datenschutz.html>.

Von: Filiz Yilmaz <notifications@github.com>
Gesendet: Mittwoch, 2. Oktober 2019 14:58
An: peeringdb/peeringdb <peeringdb@noreply.github.com>
Cc: Schmidt, Thomas <Thomas.Schmidt@business.pyur.com>; Mention <mention@noreply.github.com>
Betreff: Re: [peeringdb/peeringdb] Problem with Private Peering Locations (#580)


@tschmidt123<https://github.com/tschmidt123> could you pls send a mail to support@peeringdb.com<mailto:support@peeringdb.com>?
Our Admin Committee can look into your case then.

**Comment by koalafil** [comment] 2019-10-02 13:16
@tschmidt123 pls give us one more day to look into it. 
Admin Com volunteers will look into it and have a follow-up with you.

**Comment by arnoldnipper** [comment] 2019-10-04 19:24
That is what the users see. They are able to select the facility but are not able to re-add
![20191004 PeeringDB 01](https://user-images.githubusercontent.com/16888757/66234185-4e7d8f80-e6ed-11e9-8191-b67de27b832a.png)

**Comment by arnoldnipper** [comment] 2019-12-22 13:44
When a user tries to re-add a previously deleted facility they get a confusing error message. As the facility itself is not deleted the user is able to select it from the drop-down. However, when creating the `netfac` the system detects that there is already a record with `status: deleted`. Hence refusing the creation. 

Fix: set `status: ok` instead of giving an error because it's clear what the user wants to do.

@peeringdb/pc +1 needed

**Comment by grizz** [comment] 2019-12-22 19:18
clear bug, +1

**Comment by shane-kerr** [comment] 2019-12-27 09:52
+1

**Comment by arnoldnipper** [comment] 2019-12-27 15:37
Suggestion: instead of displaying an error message, simply re-add the facility. In more technical words. Set `status: deleted` to `status: ok`

**Comment by mcmanuss8** [comment] 2020-01-03 15:48
+1

**Comment by grizz** [comment] 2020-01-09 07:00
For implementation clarity, after rereading this (and I am very terrible at German), we're specifically talking about the `netfac` object, not changing status on the `fac` object, right?

**Comment by arnoldnipper** [comment] 2020-01-09 08:53
Exactly, we are talking about the `netfac` object.  This seems to be clear. As if the `fac` object would have been deleted, it would not be selectable from the drop-down.

**Comment by koalafil** [comment] 2020-06-01 09:47
Can we have the Release Notes pls?

**Comment by arnoldnipper** [comment] 2020-06-02 19:31
**Release Note**

Bug fix for an unclear behaviour. If a connection from a network to a facility was deleted the user was unable to re-add this connection by themselves and an unclear error message was given. Now, the user is able to re-add the connection.

**Comment by schadom** [comment] 2020-06-06 16:12
> **Release Note**
> 
> Bug fix for an unclear behaviour. If a connection from a network to a facility was deleted the user was unable to re-add this connection by themselves and an unclear error message was given. Now, the user is able to re-add the connection.

Unfortunately this still seems to be broken...

![broken_pdb](https://user-images.githubusercontent.com/33547308/83948943-2a94bf80-a821-11ea-9302-7526264e9240.png)

Thanks

**Comment by arnoldnipper** [comment] 2020-06-06 23:37
@schadom, sure ... it will be fixed with the next release. Please send an email to support@peeringdb.com and they will be happy to help

**Comment by vegu** [comment] 2020-06-16 10:39
I am having troubles reproducing this the way it is described. 

I tried the following on beta:

1. Deleted a Local Facility (ixfac) from an exchange. Then re-added it.
2. Deleted a Peering Facility (netfac) from a network. Then re-added it.

No error messages, and object re-added successfully in both attempts.

The default behaviour when deleted objects are blocking like this is already to undelete the object, so I am thinking this might be something more intermediate caused by another underlying issue.

The original ticket is from sep 2019, and i recall fixing a bug related to this as part of some other issue in one of the recent releases, but as this has happened again 10 days ago there clearly is something else going on still.

As of now i have found two ways to reproduce the above error:

1. The requesting user does not have the permissions to update the blocking netfac/ixfac (this seems unlikely in @schadom's case as he is an admin of that ix)
2. The ixfac was already added, but the browser was showing an old list.

@arnoldnipper  Do we have any logs on how the issue was resolved for @schadom ?

**Comment by arnoldnipper** [comment] 2020-06-16 11:19
@vegu, did you try as a regular user? It doesn't happen when you are a superuser

**Comment by vegu** [comment] 2020-06-16 12:36
@arnoldnipper i did, no luck - are you able to reproduce it with a regular user? if so which user?

**Comment by arnoldnipper** [comment] 2020-06-16 16:31
@vegu 

 * https://beta.peeringdb.com
 * user anipper3 (admin, but not superuser account for DE-CIX)
 * added "ILK Datacenter Karlsruhe TPK1 Albert-Nestler-Straße 8"
 * deleted "ILK Datacenter Karlsruhe TPK1 Albert-Nestler-Straße 8
 * trying to add "ILK Datacenter Karlsruhe TPK1 Albert-Nestler-Straße 8" results in the wkn error

![20200616 PeeringDB 00](https://user-images.githubusercontent.com/16888757/84801412-6db01900-afff-11ea-8f92-72f735d57fdf.png)

**Comment by vegu** [comment] 2020-06-17 06:39
@arnoldnipper thanks this was helpful.

Cause appears to be running with a non-english translation. Can reproduce as soon as i switch to german. My guess is the error message gets translated too early and is thus never caught / handled correctly.

**Comment by arnoldnipper** [comment] 2020-06-17 13:32
@vegu why did I expect the SW being language ignorant?

**Comment by vegu** [comment] 2020-06-17 17:55
Fair question - of course it is supposed to be language ignorant.

This is a bit of an edge case, with an error that is raised on the database level that is then propagated through django to the point where we deal with it during rest api validation.

We need  to obtain the fields that caused the unique contraint issue in order to identify the object and see if it qualifies for restoration (undelet). Alas the only way to obtain said fields is to parse the actual error message.

I suspect django translates the message at some point before django-rest-framework hands it to us to deal with it. Unexpected, but in the fix we are parsing the message in a way that will be language ignorant.

Does that make sense?

**Comment by arnoldnipper** [comment] 2020-06-17 18:15
Thanks for the background information, @vegu

**Closed** 2020-06-24 17:55 UTC
Labels: In a Quote, Minor, bug
