### ISSUE TITLE
ASN not visible via GUI

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1041] opened 2021-08-27 10:27 UTC
**Describe the bug**
Searching for the ASN does not reveal anything, sometimes. However, it is in the DB and shows up via the API.

**To Reproduce**

https://peeringdb.com/search?q=133929

```
curl -sG https://www.peeringdb.com/api/net --data-urlencode asn=133929 --data-urlencode since=1 --data-urlencode depth=0 | jq '.data[]'
{
  "id": 27823,
  "org_id": 30332,
  "name": "TWOWIN NETWORK",
  "aka": "TWOWIN",
  "name_long": "",
  "website": "http://www.fnetlink.com",
  "asn": 133929,
  "looking_glass": "",
  "route_server": "",
  "irr_as_set": "AS-TWOWINCOLIMITED",
  "info_type": "Network Services",
  "info_prefixes4": 32,
  "info_prefixes6": 1,
  "info_traffic": "",
  "info_ratio": "Not Disclosed",
  "info_scope": "Global",
  "info_unicast": true,
  "info_multicast": false,
  "info_ipv6": true,
  "info_never_via_route_servers": false,
  "ix_count": 1,
  "fac_count": 0,
  "notes": "www.fnetlink.com",
  "netixlan_updated": "2021-08-27T07:54:00.667549Z",
  "netfac_updated": null,
  "poc_updated": "2021-08-27T01:34:08Z",
  "policy_url": "",
  "policy_general": "Open",
  "policy_locations": "Not Required",
  "policy_ratio": false,
  "policy_contracts": "Not Required",
  "allow_ixp_update": true,
  "created": "2021-08-26T20:38:46Z",
  "updated": "2021-08-27T07:54:01Z",
  "status": "ok"
}
```

Another one is https://peeringdb.com/search?q=142428 atm

**Expected behavior**
https://peeringdb.com/search?q=133929 always should show the ASN

**Who is affected by the problem?**
Owner, Users, AC

**What is the impact?**
Confusion

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**What are the proposed actions?**
bugfix

**What is the proposed priority?**
urgent

**Additional context**
- https://peeringdb.deskpro.com/agent/#app.tickets,inbox:archive_resolved,t.o:62780,vis:6
- Could be related tp #1009

**Comment by arnoldnipper** [comment] 2021-09-02 07:48
**PRIORITY URGENT: Breaking AC's ability to do their job**

@peeringdb/20c, please have a look into it and verify. Same for @peeringdb/ac

**Comment by vegu** [comment] 2021-09-02 12:38
@arnoldnipper this is waiting on #1009 - afaik the current re-index job is set to run less frequently to cut down on error messages caused by #1009, so it will take longer for new asns to appear.

Currently new asns should appear in the search within 15 minutes. I am curious if any longer timespans have been observed in the past today or yesterday as i am trying to determine if what we are seeing is simply caused by the current slow re-index delay or a separate bug.

thanks

**Comment by leovegoda** [comment] 2022-02-17 18:28
These networks now show properly in web search. Is this still a problem for the AC @arnoldnipper ?

**Comment by arnoldnipper** [comment] 2022-02-17 20:05
If, I will document here

**Comment by leovegoda** [comment] 2022-11-18 17:59
@arnoldnipper has this problem been resolved?

**Comment by leovegoda** [comment] 2023-05-02 15:36
I'm closing this issue as there have not been any cases reported for 6 months

**Closed by leovegoda** 2023-05-02 15:36 UTC
Labels: bug, AC
