### ISSUE TITLE
Allow for username retrieval/recovery

### ISSUE THREAD

**Issue by daydr3am3r** [peeringdb/peeringdb#42] opened 2016-08-03 15:20 UTC
Hiya,

It would be great if a username recovery functionality would exist alongside password recovery. Users could enter their email address and have their username sent to them, just like in password recovery.

**Comment by arnoldnipper** [comment] 2016-08-04 08:47
Suggestion: get rid of the username. Iirc PDB currently only allows an e-mail address to be used once. Hence use the e-mail address as username.

For existing usernames != e-mail shoot an e-mail to support.

**Comment by daydr3am3r** [comment] 2016-08-04 09:19
Just going with email addresses as usernames would also be an acceptable solution for me.

**Comment by grizz** [comment] 2016-08-04 09:19
There are a lot of duplicate email addresses left over from PDB 1.0, so that's not possible

**Comment by arnoldnipper** [comment] 2016-08-04 09:35
@grizz ... let's get the shit out!

**Comment by mcmanuss8** [comment] 2016-08-04 15:47
So we ran into a similar problem when we migrated to email only addresses. The solution was to make all new user names == their email address. Then for older uses we would have them migrate to an email based username the next time they logged in. 
Duplicate email addresses get solved pretty quickly then because the first time you login with one account, it gets moved to an email-based username. If you try to login with the other account later, it forces you to pick a unique email for that account.

Any users who hadn't migrated after some number of months were either deactivated or forcibly migrated. Obviously the forcible migration doesn't work for users with dupe emails, but maybe the problem isn't so bad. How many are there? If we do the above steps and, after a year, we only have a few stragglers who can't be migrated because their email is in use elsewhere and they haven't logged in - will they even care? :)

**Comment by grizz** [comment] 2016-12-01 21:52
@arnoldnipper it's really a matter of policy, the same person might want to have multiple users with different permissions for API usage.

**Comment by arnoldnipper** [comment] 2016-12-02 19:02
I'm don't care meanwhile, @grizz

**Comment by grizz** [comment] 2016-12-02 20:19
Ok, going to set this as bug to add username retrieval.

**Comment by daydr3am3r** [comment] 2017-06-21 12:23
Hi. Any updates on this? I understand the issue needs discussion but OTOH it doesn't feel overly complicated.. @grizz are there indeed cases of people having multiple accounts based on permission?  If so, could it be an approach to just associate a different email for those accounts?

**Comment by arnoldnipper** [comment] 2017-06-21 12:32
@daydr3am3r , it simply did not yet made it to the sprint. See http://docs.peeringdb.com/committee/product/ on how the PC works

**Comment by daydr3am3r** [comment] 2017-06-21 23:35
@arnoldnipper thank you for the fast reply. I'm not sure what the exact status of the enhancement is though. Not making it to the sprint might mean a number of different things: Was a user story/epic been created already but is currently Iceboxed? Or has the issue not been discussed yet? Or was it discussed and a satisfactory solution wasn't found?

OT: There is are a couple of typos in that URL, "legitmate" should read "legitimate" and "pulled it" probably should read just "pulled", if I understand the context correctly.

**Comment by arnoldnipper** [comment] 2017-06-26 10:49
I've moved it to backlog. From there it might be forwarded to "PC candidates" and sprint

**Comment by grizz** [comment] 2017-06-29 04:58
@daydr3am3r Thanks for letting us know about the typos, fixed in https://github.com/peeringdb/docs/commit/ca9b212a5e434f5b8a51a586ddfc71ef61c7104c

**Comment by vegu** [comment] 2017-12-07 08:46
This ticket raises the issue of multiple users sharing the same email - which complicates the implementation of this a bit.

There are currently **240 unique email addresses** in the database that have at least 2 users associated with them.

The `needs discussion` label was removed but no solution was offered. Was an internal conclusion reached on how to approach this problem? 

If not i can see two obvious ways to go about this that are within scope of this ticket.

**Solution A**

A username reset similar to the password reset. If an email address is entered that has multiple users associated with it the action will be blocked and the requesting user will be notified to contact support for manual assistance in username retrieval / reset.

**Solution B**

Allow user to retrieve a list of all usernames associated to the specified email address

1. user requests username retrieval for email address
2. url gets emailed to user
3. user goes to url, gets a list of usernames associated to the specified email


Please advise on how you want this implemented.

**Comment by arnoldnipper** [comment] 2017-12-07 08:58
I would like to add

**Solution C**

Get rid of multiple users per email address

**Comment by vegu** [comment] 2017-12-07 09:06
> I would like to add
> 
> Solution C
> 
> Get rid of multiple users per email address

Should that not be it's own ticket then. While it would definitely make implementation of this more straight forward it goes beyond username retrieval, and surely will affect other areas of the site as well?

**Comment by daydr3am3r** [comment] 2017-12-07 09:44
A couple of thoughts:

Putting API usage aside for a minute, and whether what I'm saying merits another ticket or not, I assume PDB does not find ideal not having username:email parity. In other words, I am assuming (and perhaps that's a big if) that if PDB could start from scratch, it would not allow the database to develop in this way, because it's now being confronted with a state of unclarity of what is cruft or not.

If my assumption is correct, I guess what would make sense would be to:
1. Implement API keys with distinct permissions functionality. The API keys could be generated by the users, similarly to what other websites offer.
2. Set and announce a flag day to all PDB users, as to configure API keys under their "primary" accounts and delete users used for API-like functionality. 
3. Provide ample reminders until materialization of the flag day.
4. On flag day, proceed to disable all accounts not having completed step 2, telling them to contact PDB support@ as to proceed with 2. before having their account re-activated.
5. For any accounts having done 2., also consolidate usernames with email addresses as @arnoldnipper suggests. Explain this change as part of 2.

**Comment by grizz** [comment] 2017-12-07 10:27
Most of this discussion should have been in a different ticket, so I'll work with the PC to separate this, but I think it's easier to carry on the conversation here and make a new ticket for username retrieval.

I previously haven't been a huge fan of API keys in general, and I know a few people who like having multiple PDB users per email, but their reasoning can be fixed with documentation. That said, I'm going to retract my previous comments and change to be in favor of issuing API keys and storing them per org. Benefits being no need for email address on a non person user when we can use the org admins for email addresses -- which comes into play a bit with #121, and API features should stay with the org.

I think we could entertain an argument with doing per net instead of org for granularity, but in practice I don't think many orgs want to separate that, and it could easily be resolved by adding an org permissions tab for API.

As a bonus, we could expand scopes from #131 and use them with the API keys in a much cleaner fashion.

To @daydr3am3r's points
> 1. Implement API keys with distinct permissions functionality. The API keys could be generated by the users, similarly to what other websites offer.

covered

> 2. Set and announce a flag day to all PDB users, as to configure API keys under their "primary" accounts and delete users used for API-like functionality.

I don't immediately like per user API keys: removing users and user permission changes both give orgs unwanted results.

> 3-5

Migration process is spot on, give them plenty of time to merge. I'd probably be in favor of automatically merging at the end, but I can see the benefits of just disabling them.

**Comment by eloos** [comment] 2017-12-30 10:50
agreed with @daydr3am3r proposal inclusive of @grizz comments, I think it makes sense to have API keys for granularity and fix the username=email over time.

**Comment by arnoldnipper** [comment] 2017-12-30 11:20
+1 as proposed

**Comment by mcmanuss8** [comment] 2018-01-04 18:09
+1

**Comment by grizz** [comment] 2018-01-05 02:46
GitHub doesn't let me move comments, so started new tickets

For this ticket, we've implemented option B

**Comment by vegu** [comment] 2018-01-05 12:55
> For this ticket, we've implemented option B

Implemented in de893d5a

**Comment by job** [comment] 2018-01-08 20:07
If this is implemented, no more votes are needed, correct?

**Comment by grizz** [comment] 2018-01-08 21:36
Correct.

**Closed** 2018-01-08 23:32 UTC
Labels: Minor, PC Candidate, enhancement
