### ISSUE TITLE
Fix CORS header

### ISSUE THREAD

**Issue by grizz** [peeringdb/peeringdb#928] opened 2021-02-01 13:07 UTC
I'm having similar issues trying to use PeeringDB JSON trying to make a notebook in observablehq.com doing a fetch from peeringDB directly.
My code: https://observablehq.com/@emileaben/country-data-scraping works around this by using a proxy, which was a pain, and still can't get a JSON fetch to work.

```
eaben@eaben-pro% curl -i "https://www.peeringdb.com/export/advanced-search/ix/json?country__in=TR&limit=250&depth=1"
HTTP/2 200 
date: Fri, 29 Jan 2021 12:06:43 GMT
content-type: application/json
content-length: 317
server: nginx
content-disposition: attachment; filename="advanced_search_export.json"
vary: Authorization, Accept-Language, Cookie
x-frame-options: SAMEORIGIN
content-language: en

{"results": [{"Name": "DE-CIX Istanbul", "Media Type": "Ethernet", "Country": "TR", "City": "Istanbul", "Networks": 37}, {"Name": "Turk-IX", "Media Type": "Ethernet", "Country": "TR", "City": "Istanbul", "Networks": 0}, {"Name": "TR-IX", "Media Type": "Ethernet", "Country": "TR", "City": "Istanbul", "Networks": 8}]}       
```                                        
Looks like that doesn't have CORS header, notably the 'Access-Control-Allow-Origin: *' is missing as far as I understand CORS restrictions.

_Originally posted by @emileaben in https://github.com/peeringdb/peeringdb/issues/78#issuecomment-769773595_

**Comment by grizz** [comment] 2021-02-01 13:08
We should take a look at this and fix or add more documentation.

**Comment by egfrank** [comment] 2021-02-05 17:11
Just also calling attention to this comment on the original issue: https://github.com/peeringdb/peeringdb/issues/78#issuecomment-770733164

It looks like the regular API response also doesn't include cors headers

**Comment by egfrank** [comment] 2021-02-05 17:49
Closing this, since it fits with our intended behavior. Right now CORS isn't enabled on the whole site, just on the API. The original commenter was trying to use CORS on the Advanced Search, which is currently not enabled. Their examples are somewhat erroneous - the curl request is missing the origin header so it's getting no CORS failure back.

This new issue addresses the question of enabling CORS on get requests for the entire site:
https://github.com/peeringdb/peeringdb/issues/936

**Closed** 2021-02-05 17:50 UTC
Labels: Minor, bug
