### ISSUE TITLE
"-" (dash) not accepted for Company URIs

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1434] opened 2023-09-03 14:37 UTC
**Describe the bug**
social_media URIs in the social media field cannot contain "-" (dash) characters. LinkedIn _does_ allow company names in the URI to contain "-". Resulting in the PeeringDB input validation returning an generic error to the user.

**To Reproduce**
1. Go to any random network object (using the frontend)
2. Click on Edit
3. Add new social_media field of any type
4. Input a Company URI containing a "-" dash character (e.g. `abc-test-company`)
5. See error
> Something went wrong.
> The server rejected your data
> Bad Request

**Expected behavior**

- A clearer error message describing what characters are allowed in the social_media field
- The user input being accepted

**Who is affected by the problem?**
Any organizations trying to input a social_media URI containing a "-" (dash) character.

**What is the impact?**
Assumed very low

**Are there security concerns?**
None

**Are there privacy concerns?**
None

**What are the proposed actions?**
Update the [regex](https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/validators.py) to permit dashes in the string. Thou not as the first or last character.

```
            elif service in ["instagram", "twitter", "tiktok", "facebook", "linkedin"]:
                # validate username
                regex = r"^(?=.{4,32}$)(?![.-])(?!.*[.]{2})[a-zA-Z0-9._]+(?<![.])$"
                matches = re.search(regex, identifier)
                if not matches:
                    raise ValidationError(
                        _("Invalid {service} username!").format(service=service)
                    )
```

**What is the proposed priority?**
Normal

**Provide a rationale for any/all of the above**

**Additional context**
LinkedIn _does_ allow company names in the URI to contain "-". Resulting in the PeeringDB input validation returning an generic error to the user.

**Comment by grizz** [comment] 2023-09-03 20:01
@netravnen good catch, thanks! You could just submit a PR since you've already got it all figured out :)

**Comment by arnoldnipper** [comment] 2023-09-04 11:40
Duplicate of #1382

**Closed by arnoldnipper** 2023-09-04 11:40 UTC
Labels: bug, Time:Quick
