### ISSUE TITLE
Merging Organization Merging Tool borken again?

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#523] opened 2019-07-10 11:56 UTC
This time the error message is even weirder
![Screenshot 2019-07-10 13 33 40](https://user-images.githubusercontent.com/16888757/60967218-6aee7380-a31a-11e9-9136-322a618b28a8.png)

**Comment by vegu** [comment] 2019-07-10 12:59
@arnoldnipper cannot reproduce on my end, can you check the javascript console (ctrl+shift+j / cmd+shift+j) and let me know what errors you get in there please

**Comment by vegu** [comment] 2019-07-10 13:02
actually this might be the same issue thats causing #524

**Comment by arnoldnipper** [comment] 2019-07-10 13:07
![Screenshot 2019-07-10 15 05 32](https://user-images.githubusercontent.com/16888757/60971437-6f1f8e80-a324-11e9-9460-371e0a4e7803.png)

**Comment by vegu** [comment] 2019-07-10 13:09
@arnoldnipper thanks - looks like something is broken with emailing, so currently any action that would cause emails to be dispatched will fail with the 502 Gateway error - since org merges also dispatch emails, this tool is also affected - we're looking into it

**Comment by grizz** [comment] 2019-07-10 15:24
Fixed with fixing outbound SSL issue.

**Closed by grizz** 2019-07-10 15:24 UTC
Labels: bug
