### ISSUE TITLE
Facility registration tool adds identifier

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#571] opened 2019-09-18 11:43 UTC
Since 2.16.0 the AUTO tool is adding "-fac$id" in the subject. 
![20190918 PeeringDB 02](https://user-images.githubusercontent.com/16888757/65145610-3f72be00-da1a-11e9-95a2-0a837f79d8d3.png)
![20190918 PeeringDB 01](https://user-images.githubusercontent.com/16888757/65145611-3f72be00-da1a-11e9-83a5-0690f8f66f47.png)

**Comment by mcmanuss8** [comment] 2019-09-18 13:53
Seems like a small bug, let's fix it
To be clear you want it not in the subject at all?

**Comment by arnoldnipper** [comment] 2019-09-18 21:41
> To be clear you want it not in the subject at all?

"-fac$id" hasn't been there and it also was not requested to be there. No idea how it made it into the code. @vegu ?

**Comment by vegu** [comment] 2019-09-21 07:06
@arnoldnipper you are correct that this was not an intentional change, and likely stems from a recent update to django-peeringdb 1.0 (not confirmed yet, but if i had to guess)

**Comment by arnoldnipper** [comment] 2019-12-18 12:09
need one more +1 to fix this bug, @peeringdb/pc

**Comment by shane-kerr** [comment] 2019-12-18 14:18
+1

Hopefully there are not a ton of other bugs from the upgrade. :wink:

**Comment by grizz** [comment] 2019-12-18 17:17
+1

**Comment by egfrank** [comment] 2020-09-01 18:02
Hello @peeringdb/ac , we're just now revisiting this issue and it seems like it has been resolved (ie I wasn't able to reproduce it and it seems like the deskprotickets on prod do not have this issue). Can someone confirm that we can close this issue?

**Comment by arnoldnipper** [comment] 2020-09-01 22:22
@egfrank yes it was fixed somehow

**Comment by egfrank** [comment] 2020-09-03 17:33
Hi @arnoldnipper, we're currently looking into this, it looks like it's a side effect from a recent django-peeringdb upgrade that added translations to class names.

For example:
https://github.com/peeringdb/django-peeringdb/blob/master/django_peeringdb/models/abstract.py#L96

**Comment by arnoldnipper** [comment] 2020-09-28 23:23
**Release note**

Fix to Admin GUI

**Closed** 2020-09-29 18:07 UTC
Labels: Minor, bug
