### ISSUE TITLE
DeskPRO creation tools borks when user exists

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#306] opened 2018-03-23 00:33 UTC
see https://peeringdb.com/cp/peeringdb_server/deskproticket/542/change/

The tool tries to create a user w/o checking whether this user already exists

**Comment by vegu** [comment] 2018-03-23 04:12
Doing a search for the email in question using the DeskPRO Api comes up with no results.

`curl -H "Authorization: key XXX" https://peeringdb.deskpro.com/api/v2/people?primary_email=XXX`

```
{
    "data": [],
    "meta": {
        "pagination": {
            "total": 0,
            "count": 0,
            "per_page": 10,
            "current_page": 1,
            "total_pages": 1
        }
    },
    "linked": {}
}
```

But when trying to create a person for that email, it fails with the dupe error email.

A couple questions:

1. The user is a deskpro agent?
2. Does the user have the email added to their account as an additional email ? Not their primary email?

If both are true, i suggest removing the secondary email from the account, as i currently dont see a way to search for persons by secondary emails so i am unable to link the email to the existing account using their API.

Searching the DeskPRO interface for that same email in the CRM search comes up empty as well btw.

**Comment by vegu** [comment] 2018-03-23 05:09
So it appears the email address belongs to a deleted agent.

I don't think there is a way for the tool to account for that using the API. Seems like an extremely quarantined issue and can most likely be resolved by simply removing that address from the deleted agent.

**Comment by arnoldnipper** [comment] 2018-03-23 08:40
@vegu I have converted this deleted agent into a user. There are still other deleted agents but all with @peeringdb.com addresses

**Comment by vegu** [comment] 2018-03-23 09:04
Re-Queued the ticket and getting a different error now, one that i cannot quite make sense of yet

`{u'status': 400, u'message': u'Request input is invalid.', u'code': u'invalid_input', u'errors': {u'fields': {u'person': {u'errors': [{u'message': u'This value should be blank.', u'code': u'empty'}]}}}}`

The only difference i can spot between the now converted user and other users is that it has a `is_contact` value of `false` while other users have it set to `true`. I have been looking on where to set that, but cannot find it in the deskpro interface.

**Comment by vegu** [comment] 2018-03-23 09:40
maybe lets have the user send an email to support@peeringdb.com and see what that does.

**Comment by arnoldnipper** [comment] 2018-03-23 10:40
See DeskPRO 16009, @vegu  ... no issues

**Comment by vegu** [comment] 2018-03-23 10:46
I was sorta hoping that an email might change whatever is different about that particular user that it's now failing like that.

I re-queued the ticket once more, same issue.

**Comment by vegu** [comment] 2018-03-23 10:49
I will try to reproduce from dev later today with that particular user, don't think i can track this down on the production environment.

**Comment by arnoldnipper** [comment] 2018-03-23 11:00
I've tried and it works now, @vegu 

curl -sG -H "Authorization: key XXX" https://peeringdb.deskpro.com/api/v2/people\?primary_email=yyy | jq '.data[].id'
1656

**Comment by vegu** [comment] 2018-03-23 11:04
That part has been working since you converted the deleted agent, but the error we are getting has changed (see https://github.com/peeringdb/peeringdb/issues/306#issuecomment-375586812). The new error makes no sense, so i was trying to figure out if there is a difference between the user you just converted and the others.

Nothing obvious jumps out, and the new error message is nonsensical to me at this point as it implies that it now wants the person field to blank during ticket submissions. Tickets from other users have been submitting fine in the meantime. So i am a bit stumped :)

**Comment by arnoldnipper** [comment] 2018-03-23 11:11
Email support@deskpro.com, please. They are very responsive usually, @vegu

**Comment by vegu** [comment] 2018-04-09 06:54
It's a bug on their end and will be fixed in the next update of the API.

As suspected, it has to do with the fact that the user owning the email address currently used to be a deleted agent that got upgraded to a user.

To resolve on our end i suggest that we free up the email address by either assigning a different email address to the user or removing the user entirely (if that's possible?). That way DeskPRO can re-use the email address and create a fresh user from it the next time a ticket is created.

**Comment by arnoldnipper** [comment] 2020-03-19 02:10
@vegu, could we again look into it ... and hopefully close it positively

**Closed** 2020-09-18 21:58 UTC
Labels: AC, bug
