### ISSUE TITLE
Single search result redirect

### ISSUE THREAD

**Issue by grzegorz-janoszka** [peeringdb/peeringdb#233] opened 2017-11-08 17:39 UTC
When you search for something and the result is only one record, it would be good to redirect to that record. For example if you search for 12345, there is only one search result returned. You need one more click to get there, while you could be redirect straight by the search page.

**Comment by arnoldnipper** [comment] 2017-11-08 20:24
This is addressed in #178 imho

**Comment by mcmanuss8** [comment] 2017-11-08 21:20
Agreed. Let's close as dupe of #178

**Comment by grzegorz-janoszka** [comment] 2017-11-08 21:30
It is not a duplicate. #178 is about going directly to AS42, but this issue is about going to ASn if there is only one search result.

**Comment by mcmanuss8** [comment] 2017-11-09 03:23
#178 said "This would also fix the mailing list thread about going straight to a result with a single record" which sounds like this issue. But #178 is closed and https://beta.peeringdb.com/search?q=12345 doesn't do the behavior you want.
So agreed, reopening

**Comment by arnoldnipper** [comment] 2017-11-09 04:32
I would then consider this a *bug* of #178 instead

**Comment by grizz** [comment] 2017-12-17 21:10
Regardless of what one searches for, if it's a single result it should goto that result

**Comment by mcmanuss8** [comment] 2020-09-09 14:59
@peeringdb/pc  let's decide - do we want to redirect to a single result if we get one?

**Comment by arnoldnipper** [comment] 2020-09-09 15:30
+1

**Comment by ynbrthr** [comment] 2020-09-09 19:17
+1

**Comment by shane-kerr** [comment] 2020-09-10 07:59
-1

I think that proposal will create an inconsistent user experience.

Unlike the AS search where a user can learn the behavior and know that an AS search will take you directly to the result, there is literally know way for a user to know what will happen as the result of a search if we implement this behavior. This is because the user cannot know how many results a generic search will get. 

Further, a user may very well be interested in the meta-data here: How many results does a given search yield? In this case, the user has to infer that there is only a single hit if they are (un)lucky enough to have a search with a single result and end up on the page about the object and not the search result page.

While UI consistency is something that can be skipped if there is a specific "win", in this case the gain is one click.

**Comment by grizz** [comment] 2020-10-27 05:30
It's hard to tell which search this is talking about. My main point has always been that enter should go to a single result in the search as you type field from the main page.

#178 was also referring to that top search box.

To Shane's point, if it's the search form that you fill out and have to hit the search button to get results, it definitely should go the results first so you can see what happened.

**Comment by leovegoda** [comment] 2021-05-12 17:37
We will be implementing improvements to advanced search soon. At its most recent meeting, the @peeringdb/pc agreed to survey users about their expectations for basic search results. Is this an issue that should be included in that survey?

**Comment by grizz** [comment] 2021-05-12 17:46
It could, I think it's fine and covers all the points to implement how I described it last.

**Comment by grizz** [comment] 2021-07-10 01:01
@leovegoda any input on this from the survey?

**Comment by leovegoda** [comment] 2021-07-12 14:14
A survey was drafted but there's not been any feedback on it yet. I want to make sure we ask the right questions before we ask users for their time.

**Comment by leovegoda** [comment] 2022-06-09 20:11
The Product Committee has decided to close this issue. There was no agreement on the concept and the issue has not been discussed for six months or longer.

**Closed by leovegoda** 2022-06-09 20:11 UTC
Labels: enhancement, Minor
