### ISSUE TITLE
create double Facilities when changing the name

### ISSUE THREAD

**Issue by robertjakub** [peeringdb/peeringdb#76] opened 2016-10-17 07:32 UTC
when changing the name of https://www.peeringdb.com/fac/2055 (remove ending exclamation point),  webpage create an additional record of this facility resulting in double record for this facility.

**Comment by vegu** [comment] 2016-10-17 09:30
Thanks for the report,

Names ending in exclamation points mark duplicate name conflicts that happened during the v1 to v2 data import in march, so the other instance of this facility you were seeing was already there, however marked as deleted and thus not visible. The fact that it became undeleted during the update action is indeed a bug, and we'll be looking into a fix.

As for this instance, i went ahead and have fixed the name of this particular facility and it should be alright now.

**Comment by vegu** [comment] 2016-10-17 10:30
fixed in 51cb1d7

Issue was caused by the reclaim logic we have in place - which states that if you own entity A which is marked as deleted and try to create an object that has a unique key conflict with entity A on certain keys ("name" in this instance) it will undelete entity A instead of raising the unique key error. 

However currently (2.0.11) this also triggers on PUT (update) requests, which caused the above error to occur, as of this fix it will be restricted to POST (create) requests, as intended.

Fix will be rolled out with 2.0.12

**Comment by vegu** [comment] 2016-11-18 17:30
moved back to open until rolled out to production

**Closed** 2016-12-01 04:51 UTC
Labels: bug
