### ISSUE TITLE
Cloudflare/AS13335 record missing in search for all networks ordered by exchanges 

### ISSUE THREAD

**Issue by tpaseka** [peeringdb/peeringdb#556] opened 2019-09-03 20:07 UTC
When searching (all fields blank, ordered by # Exchanges) The following result is returned: 

![image](https://user-images.githubusercontent.com/2107473/64204188-1105b800-ce4a-11e9-9d0c-67817c7c0622.png)

This is missing Cloudflare/AS13335. When searching the Cloudflare record, you can see the number of exchanges is 222:

![image](https://user-images.githubusercontent.com/2107473/64204244-34306780-ce4a-11e9-8561-4c5f034a14a4.png)

Some bug causing this record not to appear in searches?

**Comment by arnoldnipper** [comment] 2019-09-03 22:37
Which browser/OS are you using, @tpaseka? If I use a blank search I get no  results at all (latest Chrome and Edge under an updated Windows10)

**Comment by job** [comment] 2019-09-03 22:45
You first have to type in something, then search, then remove what you
typed from the search field so everything is blank, and then you get
everything. Clunky

I’d be interested to learn how Tom gets there, same way?

**Comment by tpaseka** [comment] 2019-09-03 22:47
OSX 10.14.6
Chrome: Version 76.0.3809.132 (Official Build) (64-bit)

yes. get there the same way (search for something, then remove everything). also noticed the facebook and microsoft networks also doesn't return under the same blank search. 

when searching network type = content, still doesn't show cloudflare, but shows facebook + microsoft.

![image](https://user-images.githubusercontent.com/2107473/64213516-166efc80-ce62-11e9-9d7d-b51f9ebaae63.png)

**Comment by arnoldnipper** [comment] 2019-09-03 22:52
> You first have to type in something, then search, then remove what you typed from the search field so everything is blank, and then you get everything. Clunky

Even if you "Reset" you still get the same result. Try typing in a blank in "Name", then search, then "Reset" and search again

**Comment by arnoldnipper** [comment] 2019-09-03 22:54
> yes. get there the same way (search for something, then remove everything). also noticed the facebook and microsoft networks also doesn't return under the same blank search.

Maybe renaming the subject makes more sense. For me it looks like the whole Advanced Search is broken somehow

**Comment by arnoldnipper** [comment] 2019-09-03 22:59
Could you please c&p the URL you have in your browser, e.g. something like "https://peeringdb.com/advanced_search?name_search=+&reftag=net"

I found out that "Reset"ting doesn't alter this URL. So of course you get the same result

**Comment by tpaseka** [comment] 2019-09-03 23:15
https://peeringdb.com/advanced_search?&reftag=net

**Comment by vegu** [comment] 2019-09-06 07:53
The advanced search is tied directly to the API and the api limits results to 250 rows max.

You can verify that this is the cause by checking the final row below the list reading "**...More than 250 entries matched your query, refine your request..**."

With that established, to clarify this a bit further:

1. ordering by clicking the column names happens in the browser, so even if you order by a different column the ordering is still applied to the same 250 results - the api currently has no way to affect sorting if i recall correctly
2. The 250 limit is in place to speed up the searches where you get many results back, if we need to make advanced search be browsable, we should implement pagination for it - the api already supports that, but need to wire the advanced search GUI to support it as well.
3. Pagination however would also mean that results need to be sortable in the api result, so that would need to be implemented as well.

cc: @job @arnoldnipper

**Comment by vegu** [comment] 2019-09-06 08:25
> You first have to type in something, then search, then remove what you
> typed from the search field so everything is blank, and then you get
> everything. Clunky

@job i agree, however with the above mentioned limits in mind and the advanced search UI not being able to actually display "everything" (16.5k networks is a lot to render to a html table) it was not designed to do blank searched - you can circumvent by doing your methodor entering an empty space like arnold did, but its not intentional design :)

**Comment by arnoldnipper** [comment] 2019-12-18 12:17
@tpaseka are you happy if we close this issue?

**Comment by arnoldnipper** [comment] 2020-09-18 20:44
> @tpaseka are you happy if we close this issue?

@tpaseka are you ok to close this issue?

**Comment by arnoldnipper** [comment] 2020-09-25 20:20
Closed as there is no response from requestor

**Closed by arnoldnipper** 2020-09-25 20:20 UTC
Labels: bug
