### ISSUE TITLE
.kmz export Notes in Description hides metadata in Google Earth Pro

### ISSUE THREAD

**Issue by AjSteller** [peeringdb/peeringdb#1501] opened 2024-01-03 19:10 UTC
**Describe the bug**
On the .kmz export, if opening in Google Earth Web, you can view all the exported fields for any facility just fine. However, in Google Earth Pro any facility that has something in the notes field also has it showing in the "Description" field which then hides all the other fields unless deleted.

**To Reproduce**
1. Download the .kmz from PeeringDB
2. Open the .kmz in Google Earth Pro - Tested on version 7.3.6.9345 (64-bit)
3. Click on any facility that shows a description, and on the map view you will only see the description and none of the other fields.

As exported (has the "Notes" field in the Description):
![image](https://github.com/peeringdb/peeringdb/assets/153139486/2b384eeb-7943-4e82-9dce-871047a83bcb)

Right-click and edit properties of the facility, and Notes are in the Description. Delete the text and click OK:
![image](https://github.com/peeringdb/peeringdb/assets/153139486/a5eba690-3cae-4570-b90f-f208b1fa0edd)

Deleted the text in the Description, and now the facility shows all the fields as expected, including the Notes field:
![image](https://github.com/peeringdb/peeringdb/assets/153139486/0e4564c7-7dd3-45f0-9e48-aeff23531d7a)

**Expected behavior**
Be able to view the table of field output when selecting any facility, without manually deleting the Description

**Who is affected by the problem?**
Anyone using the .kmz export and viewing in Google Earth Pro

**What is the impact?**
Ease of use affected, most of the field data is hidden for any Facility that has any text in the Notes field when using Google Earth Pro, unless you manually delete the description to allow it to show the other fields

**Are there security concerns?**
No

**Are there privacy concerns?**
No

**What are the proposed actions?**
Change the export to NOT include the "Notes" field in the "Description", the Notes field is already viewable when it exists in the data when not in Description and having it in the Description doesn't seem to provide any value that I can tell. I am unsure how any other mapping software may treat the data as I have only used the two versions of Google Earth to view .kmz files.

**What is the proposed priority?**
Not urgent/Low priority

**Provide a rationale for any/all of the above**
This is simply an ease of use issue, it only really affects users that are using Google Earth Pro as opposed to the web version. Not sure what the split is on people using Pro vs Web so unknown user base affected.

**Additional context**
As mentioned above, this doesn't affect the way Google Earth Web shows the data as all the fields are still shown when there is a description. Having the Notes duplicated in the description is still redundant though since it's already in the Notes field, so this will potentially reduce file size and clutter even for those that use the Web version. Example view in Google Earth Web showing the duplication:

![image](https://github.com/peeringdb/peeringdb/assets/153139486/13a5c229-5537-4a08-a9bd-c7b267fdde2d)

**Comment by martinhannigan** [comment] 2024-01-05 01:30
Anthony, I think this is the same one as this issue: https://github.com/peeringdb/peeringdb/issues/1475 and its in queue to be fixed shortly. HTH, Thanks, Martin

**Comment by martinhannigan** [comment] 2024-01-10 16:19
@leovegoda should we mark this as duplicate of [1475](https://github.com/peeringdb/peeringdb/issues/1475) and close?  Thanks leo.

**Comment by leovegoda** [comment] 2024-01-10 18:09
@martinhannigan If we get enough votes from the @peeringdb/pc to do wither of these then we'll close both when the feature enhancement is deployed. At the moment, we need more +1s.

**Comment by martinhannigan** [comment] 2024-01-10 19:50
Why do you think this isn't a duplicate of 1475?

**Comment by leovegoda** [comment] 2024-01-10 20:51
@martinhannigan I'm not arguing that. I'm noting that we can't do wither if there are no +1s from PC members. I agree they look very similar

**Comment by grizz** [comment] 2024-01-13 02:49
@AjSteller thanks for all the extra work testing and verifying the cause!

Will be fixed with #1489

**Comment by leovegoda** [comment] 2024-08-28 19:29
Should now be fixed through other released code

**Closed by leovegoda** 2024-08-28 19:29 UTC
Labels: bug
