### ISSUE TITLE
higher contrast with the color scheme

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#65] opened 2016-09-08 14:20 UTC
http://ubersmith.peeringdb.com/admin/supportmgr/ticket_view.php?ticket=10833

I am digging the new design but would love to have an accessible view in a
future release that has higher contrast with the color scheme.

Thanks much and keep up the great work,

-Henry
## 

Henry Helmes

Phone: (202) 480-5976

**Comment by vegu** [comment] 2017-12-13 08:37
@arnoldnipper -I think this may be a dupe of #159, which was released with the last version, i think this can be closed

**Closed** 2017-12-13 10:00 UTC
Labels: enhancement, usability
