### ISSUE TITLE
Make passwordless login possible with FIDO U2F

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#760] opened 2020-07-12 13:08 UTC
Now that TOTP support has been added, I think it is time for another UX improvement: making passwordless authenticating possible using the FIDO U2F standard! :-)

https://fidoalliance.org/wp-content/uploads/FIDO-enabling-web-applications_Noor.pdf

If an user has a FIDO U2F compatible authentication device (such as Yubico Yubikey model 4 or model 5) it should be possible to configure the public key of that device in their profile page.

An admin of an organization should be able to reset the U2F tokens for any user in that organization to help them recover their account in case a U2F device breaks or gets lost. Users should be able to configure multiple U2F tokens (general expectation is that each user has 2 or more U2F devices for resiliency). 

I believe U2F is not only user friendlier, but also more secure than TOTP. (And TOTP of course was a great improvement over merely username + password).

**Comment by arnoldnipper** [comment] 2020-07-12 20:08
+1

**Comment by ynbrthr** [comment] 2020-07-16 23:07
+1

**Comment by shane-kerr** [comment] 2020-07-21 15:50
+1

**Comment by dcorbe** [comment] 2020-07-28 17:31
This is something I'm working on and testing locally.   PR inbound.

**Comment by grizz** [comment] 2020-08-14 15:28
@dcorbe any update on this?

**Comment by dcorbe** [comment] 2020-08-24 13:35
@grizz sorry for the delay.   Been a busy couple of weeks.   I'm still here though and If nobody else is working on this I'd like to jump back on it.

**Comment by dcorbe** [comment] 2020-08-27 07:35
I could actually stand to be hit with a cluebat here.   I can't seem to get an up-to-date table structure up and running.   The migrations fail to apply on a sync'd dataset.   I've also tried rebuilding the migrations and django complains about circular dependencies, so I'm at a bit of a loss.  

Is there a way to just simply get a database dump with the django_migrations table in tact?

**Comment by grizz** [comment] 2020-08-27 16:09
@dcorbe Hrm, have you tried dropping the db and syncing from scratch with the new releases we just shipped? Otherwise, can you paste what you're seeing? Happy to meet on IRC or somewhere real time to see what's going on as well.

#724 is going to be one of the next things we tackle, which would fix that issue

**Comment by dcorbe** [comment] 2020-08-29 16:50
@grizz So, are you suggesting that I build a container out of one of the tagged releases and use that to sync my data?  

I'd love to get on IRC and have a conversation about what I've been asked to do and how to proceed.   What network are you on and what's your nick?

Thank you!

**Comment by grizz** [comment] 2020-08-31 14:49
No, I'm saying once that issue is done, it should just work out of the box.

The versions we just released should sync correctly now, so I would upgrade and try again.

grizz on freenode or thz, or grizz@20c.com -- might have to email first, I don't check IRC as often as I used to :)

**Comment by mcmanuss8** [comment] 2020-12-23 19:05
@dcorbe if you're still interested in working on this issue, we now have https://github.com/peeringdb/peeringdb/blob/master/docs/container.md which makes it much simpler to setup a development environment. Feedback on that is welcome too!

**Comment by grizz** [comment] 2021-09-23 15:25
Dupe of #692

**Closed by grizz** 2021-09-23 15:25 UTC
Labels: Hourly
