### ISSUE TITLE
Third party IXP updates clobbering first party data

### ISSUE THREAD

**Issue by nbakker** [peeringdb/peeringdb#513] opened 2019-06-07 14:55 UTC
Data entered into PeeringDB by its participants should under normal circumstances not be modified without consent of those participants.

PeeringDB has a setting named "Allow IXP Update" the description of which reads
"If enabled, an ixp may manage this network's entry in their peering list".

Regardless of whether this setting is enabled, IX-F imports allow entries to be removed.

There are four problems with this.

1. Data entered by their owners is being removed
2. There is no audit trail to make obvious what happened
3. There is a documented history of these updates being incorrect (e.g. [PDB #00016892], [PDB #00021905])
4. The setting that ostensibly prohibits this is nonfunctional.

The IX-F functionality was added for ease of use for operators who wanted it (by opting in via the setting above) and to resolve possible conflicts where stale data is left in a peering record after an operator disconnects from an IXP and the IP address is recycled (see #122).  
In the first case, without opt-in no changes should be applied, and in the second case, unless there is a clear conflict, no changes should be applied, and even when there is, there should be manual review by an admin.  
In all cases, network entry owners should be able to easily find out what happened.

**Comment by mcmanuss8** [comment] 2019-06-07 15:12
This sounds like a bug. If we're not honoring the Allow IXP Update flag we should fix that

**Comment by ianainet** [comment] 2019-06-07 15:33
If "Allow IXP Update" flag is _not_ set, the user entered data should be considered canonical - with one exception.

If the user enters data known to be wrong (e.g. you put my IXP IP address into your record), then PDB will _delete_ the offending data. It should not insert new data. In this example, the IXF is considered canonical. While the user has an IP address on the exchange, the exchange "owns" the IP addresses, and their records are considered superior to the user-entered data.

**Comment by nbakker** [comment] 2019-06-07 15:48
@ianainet:
> If the user enters data known to be wrong (e.g. you put my IXP IP address into your record), then PDB will _delete_ the offending data. It should not insert new data. In this example, the IXF is considered canonical.

If you can, please review the tickets. You're describing the ideal situation, but we're not there, and we need additional protections put in place to avoid the completely predictable automation screw-ups.


> While the user has an IP address on the exchange, the exchange "owns" the IP addresses, and their records are considered superior to the user-entered data.

The exchange may "own" the IP address, but I "own" all data under my entry that I put in.

**Comment by ianainet** [comment] 2019-06-07 15:59
@nbakker: We are in agreement. I was stating PDB's policy. If the software is not implementing the policy correctly, we can and will fix it.

Thank you for bringing it to our attention. I think overall the PDB does a most excellent job of protecting user data, but everyone can make a mistake - either a bug in code or by misinterpreting the the requirements. I honestly believe no one is intentionally trying to upset users. Please assume at least good intent, and give us some time to research.

I said in my re-election platform that I would religiously guard user data. This is the type of thing I meant, and I will keep my promise.

**Comment by nbakker** [comment] 2019-06-07 16:02
Thanks @ianainet. I hope I proposed a few useful paths to follow in my original issue description.

**Comment by arnoldnipper** [comment] 2019-06-07 21:10
> Thanks @ianainet. I hope I proposed a few useful paths to follow in my original issue description.

@nbakker please see https://github.com/peeringdb/peeringdb/issues/505 ... additionally I could see to modify the current procedure to first email a network and only deleting an entry if warned x times.

The problem currently is that if the IX makes on error in its IX-F export an entry is removed and it will not be re-added.

**Comment by eloos** [comment] 2019-06-19 19:28
Does this force us to adopt a policy as to how we incorporate external information into our model? cfr. CAIDA suggestion. In other words, if someone decides that their network entry should not be managed by the 'Allow IXP update', should we relfect somehow the source and the status? i.e. "we have an IX-F import and it says this IP is wrong" but then in more machine readable form

**Comment by arnoldnipper** [comment] 2019-06-19 20:01
Imho a better approach would be to have a clear definition of who _owns_ the data. Or iow who is the _authoratative_ source. In the case given, the networks would decide whether it would show that it is connected to an IX or not. However, the IX would be able to overrule in case the network is not and also overrule value of IPv4/IPv6 (and maybe speed as well).

**Comment by nbakker** [comment] 2019-06-20 08:40
@arnoldnipper It seems we're in agreement. Clearly the network operator that actually configures the IP addresses on peering routers would be the best authority. I'm sure @ianainet would agree. The same would apply to indicating presence at a datacenter facility: that information is up to the network, not to the facility, to have included or not.

So then we need two things:

1. For networks that have explicitly opted in, allow IX-F data to automatically add, update, or remove IXP peering entries (IPs/speeds/routeserver checkmark)
2. For networks that haven't and a dispute arises about an IP address, define an escalation path to have information corrected if such a procedure doesn't exist already.

The third thing that we currently appear to have is that even without opt-in, IX-F data will silently remove entries, and possibly more. Please see the linked PeeringDB support tickets for clear cases where this was unwanted - and unacceptable - behaviour.

**Comment by arnoldnipper** [comment] 2019-06-20 11:08
@nbakker authority for IP address is with the IX. So there never is a dispute. There may be a discrepancy, however.

Imho we should work on #505 quickly. That will fix most if not all of the issues

**Comment by robwdwd** [comment] 2019-06-26 13:45
This is something I have just come across in that despite us not opting-in to allow the IX to update our entry we have had an entry removed from our peering record. Despite us entering correct information the entry was removed because the IX had incorrectly marked us as not connected when we were.

I know this "feature" helps to keep the data consistent. But since at the moment it silently removes entries it worries me that any mistake by an IX in it's member list feed means that as a network operator we then have to manually add back this entry (if we notice) and we shouldn't have to do that.

In my opinion the network record should belong to the network operator and unless specifically opted in the IXs should not be able to make any changes, even if we make a mistake, without us verifying it first. So yes #505 is a good idea but just simply removing data is a very bad one. 

I would prefer a notification either via e-mail and/or on the web front end itself marking an entry as a mismatch between IX data and the data that was entered by the network operator. So it's not removed but flagged as a mismatch that may need correcting and then it's up to the network operator to either correct it if it's wrong or leave it if it's the IX that's made the mistake (which would hopefully be fixed in the next import of IX data). The mismatch flag could be added into the API data so other network operators who use peeringdb data to configure peers can use that flag in a way they see fit.

**Comment by as44980** [comment] 2019-07-18 16:33
I have also experienced this  when adding the IP's allocated by an IXP for a new connection to the net record while the port was in the provisioning process, with the expectation this would assist with allowing potential peers to setup sessions in advance..

However despite not having opted in to "Allow IXP Update", I found the IP's which had been allocated to this network for use at this IX has been removed...  

I wasn't sure if this was expected behavior, but from the thread above it sounds like it is.

If so then I have two concerns, firstly that this appears to happen silently and without the network who submitted the data being notified in any way..

But more significantly that this sets a precedent that IXP's and facility operators can overrule user submitted data, at least as long as they do so in an automated fashion..

Which opens up the can of worms about how many peoples automation could be impacted if a corrupted IX-F json upload from an IXP decided that none of the user submitted data was valid :/

**Comment by nbakker** [comment] 2019-07-18 16:37
@as44980 You hit the nail on the head. And the behaviour isn't expected at all, otherwise we wouldn't all be here.

**Comment by fkorsback** [comment] 2019-08-02 13:46
Just wanted to chime in here and also show my support for @nbakker and the gang. We have been getting entries removed for ports that are currently undergoing a provision and is not in the IXPDB database. And therefore we have not been able to "pre-groom" peering on future exchangepoints for this reason. We simply can not peer over exchangepoints unless there is a entry in PeeringDB. I very much like that the button "Allow IXP Update Yes/No" is working on any kind of records under any kind of circumstance. I.e no silent deletes.

**Comment by fkorsback** [comment] 2019-08-02 14:54
Basically the same discussion is going on over at #518 aswell. 

Feel free to chime folks of #513 :)

**Comment by ccaputo** [comment] 2019-08-02 20:36
Related: https://github.com/peeringdb/peeringdb/issues/540

**Comment by arnoldnipper** [comment] 2019-12-27 14:11
@nbakker would you mind to look at #585 where part of this issue is addressed? The other part will be addressed in the Data Ownership TF. If you still think this issue addresses a slightly different issue, please let us know. Otherwise, please close it.

**Comment by koalafil** [comment] 2020-04-13 13:32
@peeringdb/pc 
Needs PC evaluation as per the new Data Ownership Policy and considering: 
https://github.com/peeringdb/peeringdb/issues/676 
https://github.com/peeringdb/peeringdb/issues/677
https://github.com/peeringdb/peeringdb/issues/681

**Comment by mcmanuss8** [comment] 2020-06-17 16:22
Will be implemented in #697

**Comment by arnoldnipper** [comment] 2020-12-06 05:29
With the new importer, this issue is now resolved

**Closed by arnoldnipper** 2020-12-06 05:29 UTC
Labels: Data Ownership TF
