### ISSUE TITLE
Some fields on the page are politically controversial

### ISSUE THREAD

**Issue by lshiychina** [peeringdb/peeringdb#552] opened 2019-08-20 19:10 UTC
The ISO-3166 code and name are used in PeeringDB's pages
However.
The official name of the standard is Codes for the representation of names of countries and their subdivisions.
so the name should be "country / region" not only "country" to prevent political arguments.

**Comment by lshiychina** [comment] 2019-08-20 19:22
LSY.CN's IXP is not a virtual physical access address such as LSY.CN Wuhan: LSHIY Group, No. 333 Jianshe Avenue, Jianghan District, Wuhan, Hubei, China, and there are ASN accessed through physical properties (including but not limited to: optical cables, cables).

**Comment by eloos** [comment] 2019-09-10 18:27
@lshiychina What political arguments? And why does adding the region solve it?

**Comment by lshiychina** [comment] 2019-09-10 22:18
If we do not add areas, there will be controversial issues in many areas (Hong Kong, Macao, Taiwan, British islands, American islands). For example, Hong Kong is a special administrative region of the People's Republic of China. On the page, only the "country" field shows that Hong Kong is "country: HK", and some areas are not countries. If there is political controversy in the subsequent single "country" section, and PeerimgDB uses ISO-3166, ISO-3166 is the international standard code of the International Organization for Standardization (ISO) for countries, regions, places of special scientific value, and the names of their SUB-ADMINISTRATIVE regions (e.g. provinces or states). The standard is formally called "Codes for the representation of names of countries and their subdivisions" in English. Wikipedia can be consulted specifically.

____________________
Shucheng Li

Wuhan LSHIY Network Technology Co., Ltd.

Tel: 86-13027142003
Email: shucheng.li@lshiy.com
Address: LSHIY Group, No. 333 Jianshe Avenue, Jianghan District, Wuhan, Hubei, China

信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender'sorganization. This mail communication is confidential.Recipientsnamed above are obligated to maintain secrecy andare not permitted to disclose the contents of thiscommunication to others.

**Comment by grizz** [comment] 2020-02-08 23:35
@lshiychina It seems like this could be fixed by renaming "Country" to "Region" or "Code" -- is that correct?

**Comment by job** [comment] 2020-02-09 02:42
ISO-3166 is about **country** codes. 

I don't think we need to change anything here. I vote for close.

**Comment by shane-kerr** [comment] 2020-02-10 10:01
Currently I have no strong feelings one way or the other.

I think that the main motivation for this would be if people were forbidden from using PeeringDB because of governments or government-like bodies. Is that the case though, even in China?

FWIW, APNIC scrupulously uses "Economy" instead of "Country", I _think_ mostly because of Chinese sensitivities.

**Comment by grizz** [comment] 2020-02-10 22:34
> FWIW, APNIC scrupulously uses "Economy" instead of "Country", I _think_ mostly because of Chinese sensitivities.

Exactly, if we can alter semantics to appease everyone, we probably should do it, it's a simple change.

**Comment by arnoldnipper** [comment] 2020-02-11 16:49
> ISO-3166 is about **country** codes.

Yes, about **country codes** but not about **countries** ... see AQ

**Comment by grizz** [comment] 2020-04-17 14:11
I'm not really sure what to do here, since we're using ISO-3166-1 which specifically doesn't deal with subdivisions of countries. I personally don't think that using an ISO spec as intended should elicit political feelings, but I'm sure that it does. :)

I see the options as:

1) close this, it is what it is, we didn't write the standard
2) re-label field from Country to ISO-3166(-1)
3) convert or add ISO-3166-2

I'm leaning towards option 2, as it would also allow us to add additional country/region information without confusing anything (and would recommend changing the field name for #625).

@peeringdb/pc Thoughts?

**Comment by mcmanuss8** [comment] 2020-04-17 14:45
It might get confusing, especially if we add in other levels of geography (like in #37), but I think "Geography" might be enough to satisfy this requirement. To pick a (maybe) less sensitive example:

Puerto Rico is a US territory. It has its own ISO-3166-1 code (PR). We would be incorrect in saying "Country: Puerto Rico" (or "Country: PR"), but fair to say "Geography: Puerto Rico". 

So +1 to changing Country to Geography to make this more generic for all cases. 
+1 to adding a tooltip to the field that says "As defined by ISO-3166-1, and extra bonus points to making that tooltip link to https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes if clicked

**Comment by grizz** [comment] 2020-04-17 15:08
I'd settle for Geography, but I think being quite specific and labeling it "ISO-3166-1" is a better choice. Especially, if we want to add ISO-3166-2 or some other geography locator code in the future.

**Comment by job** [comment] 2020-04-17 15:12
Option one. No need for change. This was a trolling action. I don't get that we *keep* wasting time on this.

**Comment by lishucheng1227** [comment] 2020-04-17 17:33
I think it would be better to use "economy", for example APNIC's Web is to use "economy"

For example this page
https://www.apnic.net/get-ip/apnic-membership/who-are-our-members/

**Comment by grizz** [comment] 2020-04-17 19:06
Apologies for re-opening this can of worms. I can see labeling it to be the name of the standard, otherwise fiddling around with words is just endless bikeshedding.

I'm changing my vote to option 1, @peeringdb/pc can we get one more +1 for that?

**Comment by ynbrthr** [comment] 2020-04-17 20:14
> 
> I'm changing my vote to option 1, @peeringdb/pc can we get one more +1 for that?

you bet! +1 for 1

**Comment by mcmanuss8** [comment] 2020-04-17 20:29
I agree the initial ask that prompted this was trolling, but it does seem a bit inaccurate to say "Country Code". Again, consider Puerto Rico, like: https://peeringdb.com/ix/2353

We also inconsistently say "Country" and "Country Code" across /ix/, /fac/, and /org/ . I'd prefer we clean that inconsistency up and squash this now before it comes up and we get trolled again in the future. 

I'm ok with any of:
Geography:
Geography Code:
ISO 3166-1 Code:

"Economy" feels accurate but also not as intuitive and maybe harder for our translators to get across in other languages. *shrug*

**Comment by arnoldnipper** [comment] 2020-04-17 20:48
+1 for ISO-3166-1 Code. We could add a hoove over to explain in more detail like "Defined code for the names of countries, dependent territories, and special areas of geographical interest"

**Comment by job** [comment] 2020-04-17 21:13
Is this really what we want to spend development minors on? I don’t think anything is broken, we know it was a troll account. It feels like waste to continue discussion. Did anyone ever hear from their coworkers or peers that the website is unclear? Let’s please move on.

**Comment by arnoldnipper** [comment] 2020-04-17 21:48
I fully agree with @mcmanuss8 that the initial ask that prompted this was trolling. But this should not refrain us from doing better and being accurate.

**Comment by arnoldnipper** [comment] 2020-12-05 02:17
**Proposal**

 * GUI/API: rename "[Cc]ountry" to "[Gg]eography". For the API object, this might have to wait until v3. However, the API should be able to understand geography when being queried

 * GUI: spell out the ISO 3166-1 alpha-2 to names

@peeringdb/pc, please comment

**Comment by leovegoda** [comment] 2021-05-20 11:49
@peeringdb/pc is this an issue we should address directly, or should we it into the broader website UX changes we want to make?

**Closed** 2022-06-09 20:08 UTC
