### ISSUE TITLE
[beta] IX-F importer: unnecessary add and update suggested

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#815] opened 2020-08-15 17:30 UTC
@vegu please check out: https://beta.peeringdb.com/net/2073

At start am seeing:

<img width="1180" alt="Screen Shot 2020-08-15 at 10 20 10 AM" src="https://user-images.githubusercontent.com/1417833/90317826-f43e8500-dee0-11ea-936e-472f1d839570.png">

and when editing and suggestions are viewed:

<img width="1158" alt="Screen Shot 2020-08-15 at 10 20 24 AM" src="https://user-images.githubusercontent.com/1417833/90317830-f99bcf80-dee0-11ea-9138-33c9942f3380.png">

It appears to me the IPv4 and IPv6 address at "UNM-Exch Canada-West" are already correct, so it is not clear to me why a hint is happening.  I suspect the bug relates to how the JSON export is arranged:

```
      "connection_list": [
        {
          "ixp_id": 0, 
          "vlan_list": [
            {
              "vlan_id": 0, 
              "ipv4": {
                "as_macro": "AS-CIPHERKEY-TRANSIT", 
                "address": "192.34.27.28"
              }
            }, 
            {
              "vlan_id": 0, 
              "ipv6": {
                "as_macro": "AS-CIPHERKEY-TRANSIT", 
                "address": "2602:ffb1:200:0:192:34:27:28"
              }
            }
          ]
        }
      ], 
```

rather than this more expected format, as an example:

```
			"connection_list": [
				{
					"vlan_list": [
						{
							"vlan_id":2,
							"ipv4":{
								"address":"206.81.81.XX"
							},
							"ipv6":{
								"address":"2001:504:16::XXXX"
							}
						}
					]
				}
			]
```

**Comment by ccaputo** [comment] 2020-08-15 17:48
MBIX has a similar JSON format, so the issue is happening with participants there too.  For example AS6939 there:

<img width="589" alt="Screen Shot 2020-08-15 at 10 47 39 AM" src="https://user-images.githubusercontent.com/1417833/90318361-c8250300-dee4-11ea-9003-abbd944ba095.png">

**Comment by vegu** [comment] 2020-08-16 10:32
>  I suspect the bug relates to how the JSON export is arranged

Able to reproduce locally - reasonable suspicion, and although we do have code in place to deal with this scenario, something is not getting handled correctly.

**Comment by grizz** [comment] 2020-08-16 12:15
Fast track, clear bug.

**Comment by arnoldnipper** [comment] 2020-08-16 17:58
I'm not sure this is a clear bug. How would e.g. two interfaces be represented when one interface has an IPV4 address only and the other an IPv6 address only?

**Comment by ccaputo** [comment] 2020-08-16 19:01
> I'm not sure this is a clear bug. How would e.g. two interfaces be represented when one interface has an IPV4 address only and the other an IPv6 address only?

I suppose similarly, but as it is, multiple IXes are representing single-interfaces in this manner, thus this will generate many superfluous conflicts in which the solution (separate entries) is worse than the present state (single entry because it is a single-interface).

**Comment by ccaputo** [comment] 2020-08-16 21:43
> I'm not sure this is a clear bug. How would e.g. two interfaces be represented when one interface has an IPV4 address only and the other an IPv6 address only?

Digging further.  A second connection would be a separate list item in the `connection_list`.  That is not what is happening here.  Rather, these are separate list items in the `vlan_list`, albeit with the same `vlan_id`.:

```
      "connection_list": [
        {
          "ixp_id": 0, 
          "vlan_list": [
            {
              "vlan_id": 0, 
              "ipv4": {
                "as_macro": "AS-CIPHERKEY-TRANSIT", 
                "address": "192.34.27.28"
              }
            }, 
            {
              "vlan_id": 0, 
              "ipv6": {
                "as_macro": "AS-CIPHERKEY-TRANSIT", 
                "address": "2602:ffb1:200:0:192:34:27:28"
              }
            }
          ]
        }
      ], 
```

Thus the code should treat those as the same connection in the same VLAN.

Here is a, IMHO good, example of two interfaces, each using two VLANs:

```
			"connection_list": [
				{
					"ixp_id":1,
					"state":"active",
					"if_list": [
						{
							"switch_id":3,
							"if_speed":20000
						}
					],
					"vlan_list": [
						{
							"vlan_id":2,
							"ipv4":{
								"address":"206.81.80.10",
								"max_prefix":5
							},
							"ipv6":{
								"address":"2001:504:16::1938",
								"max_prefix":1
							}
						},
						{
							"vlan_id":3,
							"ipv4":{
								"address":"206.81.82.10",
								"max_prefix":5,
								"routeserver":true
							},
							"ipv6":{
								"address":"2001:504:16:1::1938",
								"max_prefix":1,
								"routeserver":true
							}
						}
					]
				},
				{
					"ixp_id":1,
					"state":"active",
					"if_list": [
						{
							"switch_id":3,
							"if_speed":20000
						}
					],
					"vlan_list": [
						{
							"vlan_id":2,
							"ipv4":{
								"address":"206.81.81.41",
								"max_prefix":5
							},
							"ipv6":{
								"address":"2001:504:16::297:0:1938",
								"max_prefix":1
							}
						},
						{
							"vlan_id":3,
							"ipv4":{
								"address":"206.81.83.41",
								"max_prefix":5,
								"routeserver":true
							},
							"ipv6":{
								"address":"2001:504:16:1:0:297:0:1938",
								"max_prefix":1,
								"routeserver":true
							}
						}
					]
				}
			]
```

**Comment by ccaputo** [comment] 2020-08-17 14:57
Related to this, along with possible heads-up to the @peeringdb/ac and @peeringdb/pc.  I've noticed that BKNIX (https://beta.peeringdb.com/ix/1025) actually has different VLANs for IPv4 & IPv6 per https://bknix.co.th/th/index.php?module=technical&content=2 and yet they are only represented by a single IX in PeeringDB.  Their IX-F JSON data correctly describes the different VLANs, and appears to describe networks that use a single circuit to connect to both VLANs (the majority), for example:

```
            "connection_list": [
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 1000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 1,
                            "ipv4": {
                                "address": "203.159.68.119",
                                "as_macro": "AS-63529-as-import-AS7693",
                                "routeserver": true,
                                "mac_addresses": [
                                    "78:da:6e:36:0e:0f"
                                ]
                            }
                        },
                        {
                            "vlan_id": 3,
                            "ipv6": {
                                "address": "2001:deb:0:68::119",
                                "as_macro": "AS-63529-as-import-AS7693",
                                "routeserver": true,
                                "mac_addresses": [
                                    "78:da:6e:36:0e:0f"
                                ]
                            }
                        }
                    ]
                }
            ]
```

and some networks that appear to have a different connection for each protocol, for example:

```
            "connection_list": [
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 10000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 1,
                            "ipv4": {
                                "address": "203.159.68.40",
                                "as_macro": "AS-AKAMAI",
                                "routeserver": true,
                                "mac_addresses": [
                                    "ec:13:db:f0:37:f1"
                                ]
                            }
                        }
                    ]
                },
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 10000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 3,
                            "ipv6": {
                                "address": "2001:deb:0:68:0:a502:940:1",
                                "as_macro": "AS-AKAMAI",
                                "routeserver": true,
                                "mac_addresses": [
                                    "ec:13:db:f0:37:0c"
                                ]
                            }
                        }
                    ]
                }
            ]
```

A challenge with this is the resulting suggestions, for example Akamai (https://beta.peeringdb.com/net/2):

![Screen Shot 2020-08-17 at 7 50 02 AM](https://user-images.githubusercontent.com/1417833/90409650-4953d580-e05e-11ea-910b-3142679bc67d.png)

In one sense, the correct data is already set, so the hints are problematic, but in another sense the data should be represented as two connections, potentially with the PeeringDB IX divided into two different IXes.  I don't know what to suggest to solve this kind of thing.

At present the BKNIX hints at https://beta.peeringdb.com/net/2 will result in a "The server rejected your data" situation.  That might be solved by fixes to existing issues, or maybe it is a new issue?

**Comment by arnoldnipper** [comment] 2020-08-17 20:55
> Related to this, along with possible heads-up to the @peeringdb/ac and @peeringdb/pc. I've noticed that BKNIX (https://beta.peeringdb.com/ix/1025) actually has different VLANs for IPv4 & IPv6

Easiest would be to fix that in PeeringDB. I.e. setting up **two** exchanges. No?

**Comment by ccaputo** [comment] 2020-08-17 21:02
> > Related to this, along with possible heads-up to the @peeringdb/ac and @peeringdb/pc. I've noticed that BKNIX (https://beta.peeringdb.com/ix/1025) actually has different VLANs for IPv4 & IPv6
> 
> Easiest would be to fix that in PeeringDB. I.e. setting up **two** exchanges. No?

I don't know.  That seems like something for the @peeringdb/ac to work out with the IX.  In a general sense, this is something we need to be aware of in terms of it potentially coming up a fair amount when the Importer is re-enabled.

**Comment by arnoldnipper** [comment] 2020-08-17 21:14
> this is something we need to be aware of in terms of it potentially coming up a fair amount when the Importer is re-enabled.

This is something we can already pre-check. No? And I'm pretty sure "fair" is "<=2" ...

**Comment by arnoldnipper** [comment] 2020-08-17 21:17
> That seems like something for the @peeringdb/ac to work out with the IX

I'm talking to Kittinan from BKNIX about the options we have. From the ixlan_id/ix_id harmonisation, we still should have tools in place to split the exchange into "BKNIX IPv4" and "BKNIX IPv6". If those tools don't work it still should be fairly easy to accomplish this task with some API calls.

**Comment by ccaputo** [comment] 2020-08-17 21:17
> > this is something we need to be aware of in terms of it potentially coming up a fair amount when the Importer is re-enabled.
> 
> This is something we can already pre-check. No? And I'm pretty sure "fair" is "<=2" ...

You may know better than me.  I simply clicked on one or two IXes and discovered this.  Since there are 100+ that haven't been examined closely, this may happen more frequently than known.

**Comment by vegu** [comment] 2020-08-18 09:32
@ccaputo @arnoldnipper 

To make sure we're all on the same page - here is a quick update from our end and what we have ready to go to beta for this ticket.

We have fixed and strengthened the logic that deals with the sanitisation of the `vlan_list` to be more peeringdb "friendly" when reasonable (according to what's laid out in this ticket so far).

In the case of multiple entries inside `vlan_list` they are combined into ipv4/ipv6 pairs by their `vlan_id`. 

Right now, If no `vlan_id` is specified it is treated as `vlan_id`=0, so the combining still happens, and the vlan_id itself is not really relevant to peeringdb other than for this purpose. However we are not entirely sure this is the correct way to go here, so please clarify if a different behaviour on missing vlan_id is required.

Finally, this is all on a **per connection basis**. So vlan ids shared across multiple connections in separate `vlan_list` lists are not aware of each other and wont result in any such combinations.

Here are some examples of sanitisation that we are currently testing, please let us know if any of those are incorrect, so we can make adjustments before going to beta. Note that `0`, `3` and `4` don't change the data as it is already good and workable for the ix-f importer.

**Examples**

<table>
<tr>
<th>#NUM</th>
<th>ORIGINAL</th>
<th>SANITISED</th>
</tr>
<tr>
<td>0</td>
<td>

```json
{
  "vlan_list": [
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
<td>

```json
{
  "vlan_list": [
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
</tr>
<tr>
<td>1</td>
<td>

```json
{
  "vlan_list": [
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.81.12"
      }
    },
    {
      "vlan_id": 2,
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
<td>

```json
{
  "vlan_list": [
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
</tr>
<tr>
<td>2</td>
<td>

```json
{
  "vlan_list": [
    {
      "ipv4": {
        "address": "206.81.81.12"
      }
    },
    {
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
<td>

```json
{
  "vlan_list": [
    {
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
</tr>
<tr>
<td>3</td>
<td>

```json
{
  "vlan_list": [
    {
      "vlan_id": 1,
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    },
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.82.12"
      },
      "ipv6": {
        "address": "2001:504:17::1234"
      }
    }
  ]
}
```

</td>
<td>

```json
{
  "vlan_list": [
    {
      "vlan_id": 1,
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    },
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.82.12"
      },
      "ipv6": {
        "address": "2001:504:17::1234"
      }
    }
  ]
}
```

</td>
</tr>
<tr>
<td>4</td>
<td>

```json
{
  "vlan_list": [
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.81.12"
      }
    },
    {
      "vlan_id": 3,
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
<td>

```json
{
  "vlan_list": [
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.81.12"
      }
    },
    {
      "vlan_id": 3,
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
</tr>
<tr>
<td>5</td>
<td>

```json
{
  "vlan_list": [
    {
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    },
    {
      "ipv4": {
        "address": "206.81.81.13"
      }
    },
    {
      "ipv6": {
        "address": "2001:504:16::1235"
      }
    }
  ]
}
```

</td>
<td>

```json
{
  "vlan_list": [
    {
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    },
    {
      "ipv4": {
        "address": "206.81.81.13"
      },
      "ipv6": {
        "address": "2001:504:16::1235"
      }
    }
  ]
}
```

</td>
</tr>
<tr>
<td>6</td>
<td>

```json
{
  "vlan_list": [
    {
      "ipv4": {
        "address": "206.81.81.11"
      }
    },
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    },
    {
      "ipv6": {
        "address": "2001:504:16::1233"
      }
    }
  ]
}
```

</td>
<td>

```json
{
  "vlan_list": [
    {
      "ipv4": {
        "address": "206.81.81.11"
      },
      "ipv6": {
        "address": "2001:504:16::1233"
      }
    },
    {
      "vlan_id": 2,
      "ipv4": {
        "address": "206.81.81.12"
      },
      "ipv6": {
        "address": "2001:504:16::1234"
      }
    }
  ]
}
```

</td>
</tr>
</table>

**Comment by arnoldnipper** [comment] 2020-08-18 13:54
> Right now, If no `vlan_id` is specified it is treated as `vlan_id`=0, so the combining still happens, and the vlan_id itself is not really relevant to peeringdb other than for this purpose. However we are not entirely sure this is the correct way to go here, so please clarify if a different behaviour on missing vlan_id is required.

Thanks for the table, @vegu. Regarding a missing `vlan_id` I'm not sure that treating it as `vlan_id`=0 is proper behaviour. I would concur if `vlan_id` is missing entirely. Otherwise, best behaviour is to disregard the entry. Do you have an example where we have mixed usage?

**Comment by vegu** [comment] 2020-08-18 14:10
@arnoldnipper haven't come across it in the field, just trying to cover as many angles as possible.

The behaviour in question is the one in example 6, correct? So if `vlan_id` is set on some entries but missing from others, it'd make more sense to skip the one's missing it entirely, is that correct?

**Comment by grizz** [comment] 2020-08-18 14:13
@arnoldnipper @ccaputo this is ready for the final beta release before production, which is happening today. I believe it's good to go into the release, if you don't feel that way, now is the time to let us know.

**Comment by arnoldnipper** [comment] 2020-08-18 14:14
> So if `vlan_id` is set on some entries but missing from others, it'd make more sense to skip the one's missing it entirely, is that correct?

That is correct. And I'm pretty sure a validator would also generate an error message in that case.

**Comment by arnoldnipper** [comment] 2020-08-18 14:16
@grizz, we have tried hard to make the release as good as possible. Let's go! And thanks again for your hard work!

**Comment by ccaputo** [comment] 2020-08-18 14:22
All looks good to me, and if @arnoldnipper thinks we should ignore records missing a `vlan_id` when some in the same JSON do have the `vlan_id`, I am okay with that.  Part of me prefers to be liberal in what we accept, but this is hopefully a rare situation.

**Comment by arnoldnipper** [comment] 2020-08-18 22:22
> Part of me prefers to be liberal in what we accept, but this is hopefully a rare situation.

I fully agree. But when the `vlan_id` is missing only sometimes best you can do is to start wild guessing. As we say "Gut gedacht, ist nicht gut gemacht".

**Comment by ccaputo** [comment] 2020-08-19 00:53
BKNIX currently has the following for Akamai:

```
            "connection_list": [
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 10000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 1,
                            "ipv4": {
                                "address": "203.159.68.40",
                                "as_macro": "AS-AKAMAI",
                                "routeserver": true,
                                "mac_addresses": [
                                    "ec:13:db:f0:37:f1"
                                ]
                            }
                        }
                    ]
                },
                {
                    "ixp_id": 1,
                    "state": "active",
                    "if_list": [
                        {
                            "switch_id": 2,
                            "if_speed": 10000
                        }
                    ],
                    "vlan_list": [
                        {
                            "vlan_id": 1,
                            "ipv6": {
                                "address": "2001:deb:0:68:0:a502:940:1",
                                "as_macro": "AS-AKAMAI",
                                "routeserver": true,
                                "mac_addresses": [
                                    "ec:13:db:f0:37:0c"
                                ]
                            }
                        }
                    ]
                }
            ]
```

Starting with:

![Screen Shot 2020-08-18 at 5 44 44 PM](https://user-images.githubusercontent.com/1417833/90579380-b2307000-e17a-11ea-90b5-1096e8ca1172.png)

Clicking Add results in "The server rejected your data":

![Screen Shot 2020-08-18 at 5 45 05 PM](https://user-images.githubusercontent.com/1417833/90579412-c7a59a00-e17a-11ea-91e6-28ce838082e1.png)

Clicking Accept and Save and then reviewing remaining BKNIX hints results in:

![Screen Shot 2020-08-18 at 5 48 50 PM](https://user-images.githubusercontent.com/1417833/90579516-1a7f5180-e17b-11ea-90db-cc9014ac526f.png)

Clicking Add and Save now works and results in two connections:

![Screen Shot 2020-08-18 at 5 49 57 PM](https://user-images.githubusercontent.com/1417833/90579561-48649600-e17b-11ea-836e-2b0edf5bb60c.png)

Since that matches the IX-F JSON data which shows two connections, the end result appears correct.  But we got here by persisting through a "The server rejected your data" message.  That is suboptimal.

Re-opening this in case it makes sense to combine the two operations in to a single operation that achieves the same result while forgoing the error.  (will remove "showstopper" from the issue name)

**Comment by egfrank** [comment] 2020-08-21 03:30
Hi @ccaputo ! I'm just catching up on this issue (ie I didn't write code for this issue specifically) so I wanted to make sure we're on the same page.

Looking at the issue above, Vegu posted `Finally, this is all on a per connection basis. So vlan ids shared across multiple connections in separate vlan_list lists are not aware of each other and wont result in any such combinations.` and as far as I understand this example falls into that bucket.

What I'm seeing is that, at first, the user is not able to accept the first hint, because adding the connection with ipaddr4 = 203.159.68.40 would overlap with the existing connection with both ipaddr4=203.159.68.40 and ipaddr6=2001:deb:0:68:0:a502:940:1. Then, once they've taken the suggestion to update that existing connection to only set the ipaddr6, they are allowed to accept the "add" hint.

Because they are currently two separate hints, I'm taking that to mean that theoretically a user may choose to dismiss the "update" hint. In which case, that error message would remain meaningful. Likewise, I'm assuming that a user might want to dismiss the "add" hint and only update the existing connection.

If you don't think that a user would ever chose to only accept one of those hints, then it would make sense to consolidate them. I'm not 100% sure what this change would entail but I'd predict that, instead of the vlan_id sanitation referenced in this issue, it would involve the same `requirement_of` logic implemented in https://git.20c.com/gh/peeringdb/peeringdb/-/issues/148.

**Comment by vegu** [comment] 2020-08-26 06:49
Split out the final issue in #828 and closing this

**Closed by vegu** 2020-08-26 06:49 UTC
Labels: Minor, bug
