### ISSUE TITLE
Add a button for IXes to flag a netixlan entry as bad

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1272] opened 2022-10-22 23:56 UTC
**Is your feature request related to a problem? Please describe.**
Currently, only ~19%  of all IXes provide IX-F JSON data. Especially, the older and smaller ones not running IXP Manager may lack resources to implement IX-F JSON.

However, they are also eager to keep the `netixlan` entries clean. ATM, they have to email [AC](@peeringdb/ac) for help.

**Who is affected by the problem?**
81% of all IXes, not having IX-F JSON at hand/enabled

**Describe the solution you'd like**
Add a button/mechanism for IXes to flag a `netixlan` entry as bad. If an entry is flagged as bad, run the normal dispute procedure.

**Do you think this feature will require a formal design?**
no

**Comment by arnoldnipper** [comment] 2022-10-23 00:11
Complements #983

**Comment by job** [comment] 2022-10-23 05:01
perhaps such a button should be called “report issue”?

**Comment by peterhelmenstine** [comment] 2022-10-26 09:48
+ yup agreed

**Comment by mcmanuss8** [comment] 2022-11-03 17:12
Dupe of #170 ?

**Comment by leovegoda** [comment] 2023-11-15 18:21
This appears to be a duplicate of #170, which is scheduled for release in January 2024. I'm closing this issue.

**Closed by leovegoda** 2023-11-15 18:21 UTC
Labels: bug, AC
