### ISSUE TITLE
API key handling inconsistencies due to www. redirect

### ISSUE THREAD

**Issue by gmazoyer** [peeringdb/peeringdb#1136] opened 2022-03-25 16:27 UTC
**Describe the bug**

API token authentication is not handled properly when being redirected to the `www` prefixed URL.

**To Reproduce**
1. Send an API request `curl -v -H "AUTHORIZATION: Api-Key BOGUS" -H "Content-Type: application/json" -L https://peeringdb.com/api/net/1`
2. Get the data from the record
3. Send an API request `curl -v -H "AUTHORIZATION: Api-Key BOGUS" -H "Content-Type: application/json" -L https://www.peeringdb.com/api/net/1`
4. Get rejected with `{"meta": {"error": "Invalid API key"}}`

**Expected behavior**
Get rejected when using an invalid API key

**Who is affected by the problem?**

Applications using PeeringDB with API keys that have been configured to send requests to `https://peeringdb.com` instead of `https://www.peeringdb.com`

**What is the impact?**

Applications not using the `www.` prefix will get limited set of data even if the authentication is correct as it looks like it bypasses the API token authentication.

**Are there security concerns?**

No

**Are there privacy concerns?**

No

**Comment by mcmanuss8** [comment] 2022-03-25 16:29
+1 clear bug 
@grizz is this something we can hotfix easily? Feels like an oversight when implementing #1117

**Comment by grizz** [comment] 2022-03-25 17:37
This is not a bug, that's how curl works by design to avoid leaking credentials. After the redirect, curl will not pass the authorization header (as can be see in the debug output there's no `> authorization: Api-Key BOGUS` line on the second request).

If you use the curl option `--location-trusted`, the header will be included after the redirect, and PDB correctly responds with 401.

@gmazoyer Thanks for the report, please reply and reopen if I missed something or misunderstood. :)

**Closed by grizz** 2022-03-25 17:37 UTC

**Comment by falz** [comment] 2022-03-25 18:04
Want to note that some peeringdb docs refer to the API without **www**. 

Should it only be accessed via www? If so, some docs may need updating. https://docs.peeringdb.com/api_specs/

**Comment by arnoldnipper** [comment] 2022-03-27 23:12
> Should it only be accessed via www? If so, some docs may need updating. https://docs.peeringdb.com/api_specs/

fixed afais
