### ISSUE TITLE
Sort simple search output human (aka alphanumerically) friendly

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1050] opened 2021-09-10 07:56 UTC
**Is your feature request related to a problem? Please describe.**
Currently, search output is sorted by object ID. However, users expect is to have the output sorted by name alphanumerically

**Who is affected by the problem?**
Everyone

**What is the impact?**
Extra work for the users

**Are there security concerns?**
no

**Are there privacy concerns?**
no

**Describe the solution you'd like**
Sort output by name alphanumerically

**Describe alternatives you've considered**
none

**Could this feature request need support from the Admin Committee?**
no

**What is the proposed priority?**
normal

**Provide a rationale for any/all of the above**

**Additional context**
Advanced search already sorts in a user-friendly way (i.e. alphanumerically)

**Comment by vegu** [comment] 2021-09-14 06:36
To clarify, with the switch to an indexed search backend results are now sorted by search score, with the highest score on top. 

If this proposal to switch back to an alphanumeric display of search results is to be implemented the changes proposed in #397 should be considered as well. (currently closed as no longer relevant with the current scored search result sorting)

**Comment by grizz** [comment] 2023-02-27 17:41
Closing this as a dupe of #1299 -- please re-open if I misunderstood.

**Closed by grizz** 2023-02-27 17:41 UTC
Labels: enhancement
