### ISSUE TITLE
Unable to access facility history - Server Error (500)

### ISSUE THREAD

**Issue by netravnen** [peeringdb/peeringdb#1320] opened 2023-01-30 10:04 UTC
**Describe the bug**

User created a [ticket (82841)](https://peeringdb.deskpro.com/agent/#app.tickets,inbox:unassigned,t.o:82841,vis:5) writing as an Org admin not being able to approve a carrier at the Org's managed facility.

> I received a request to accept a new carrier in my DC, and when I clicked to accept, the button changed the colour and then it back green again.

Tried what the org admin wrote was not able to complete. Succeeded without issue.

Next, went to the control panel, trying to access the facility history, and hit the described 500 error code instead of the facility history page.

**To Reproduce**

1. Go to https://www.peeringdb.com/cp/peeringdb_server/facility/12707/change/
2. Click on history
3. See error `Server Error (500)`

**Expected behavior**

Access the history of a carrier object shows the expected page normally (HTTP 200 OK).

**Who is affected by the problem?**

PeeringDB Admincom, etc.

**What is the impact?**

Unable to access object history

**Are there security concerns?**

N/A

**Are there privacy concerns?**

N/A

**What are the proposed actions?**

Validate if this is a bug, or data validation error?

**What is the proposed priority?**

N/A

**Provide a rationale for any/all of the above**

N/A

**Additional context**

N/A

**Comment by arnoldnipper** [comment] 2023-02-01 04:19
Duplicate of #1096

**Closed** 2023-02-01 04:20 UTC
