### ISSUE TITLE
Q: translate.peeringdb.com

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#442] opened 2019-02-24 00:31 UTC
With the new layout we also had minor changes in content which have to be translated again. here are a few questions:

1. What is the process of importing new strings into translate?

2. And also to have translated content make it into production then?

3. Obviously headings didn't make it into translation (see picture attached)
![20190227 peeringdb 00](https://user-images.githubusercontent.com/16888757/53456282-18c54980-3a2e-11e9-889f-26e1fe387215.png)

**Comment by grizz** [comment] 2019-02-28 13:20
Oh, we have to run a script for that, I mistakenly thought that was cron'd, but it doesn't look like it.

**Comment by arnoldnipper** [comment] 2019-03-01 02:26
> Oh, we have to run a script for that, I mistakenly thought that was cron'd, but it doesn't look like it.

Tnx, @grizz .  That does most likely answer Q1 and Q2, but I can't see how it answers Q3

**Comment by grizz** [comment] 2019-03-01 02:30
@arnoldnipper I'm guessing the headings were changed since last run, I'll have to see. The script takes everything that is able to be translated. If they don't get put in there, we'll have to look into it.

**Comment by arnoldnipper** [comment] 2019-03-01 02:47
@grizz ... could you please run the script and cron it. And how often will the cron run?

**Comment by grizz** [comment] 2019-03-01 02:50
@arnoldnipper ran now, Peer Name is in German untranslated.

When I went to run it, I remembered we decided to not cron it until we had run it a few times to make sure it's running as intended, feel free to check it out.

**Comment by arnoldnipper** [comment] 2019-03-01 06:26
Well ... I guess we don't understand each other. Wehn I switch to German there still is not translated text. However when I look at translate it says it's 100% tarnslated
![20190301 peeringdb server german peeringdb translations](https://user-images.githubusercontent.com/16888757/53620459-57583100-3bf3-11e9-8e95-9c88f2a42fda.png)
![20190301 peeringdb 00](https://user-images.githubusercontent.com/16888757/53620468-5cb57b80-3bf3-11e9-9395-fd0463544beb.png)

**Comment by arnoldnipper** [comment] 2019-03-01 06:30
> @arnoldnipper ran now, Peer Name is in German untranslated.
> 
> When I went to run it, I remembered we decided to not cron it until we had run it a few times to make sure it's running as intended, feel free to check it out.

> @arnoldnipper ran now, Peer Name is in German untranslated.

In the picture I attached it's not about "Peer Name" which btw *is* translated to "Peername". It's about the heading "Peers at this Exchange Point".

**Comment by grizz** [comment] 2019-03-01 06:42
(We're all new to weblate) -- I think you have to go to strings waiting for review to see some of them.

Yeah, it appears "Peers at this Exchange Point" didn't make it into the translation files, we'll take a look at it.

**Comment by vegu** [comment] 2019-03-01 15:12
string was missing the locale filter in the template, pushed a fix in 848b05b, should be there after next rollout.

If we find more of these instances where strings are missing for locale we should probably maintain a ticket just for those.

**Comment by arnoldnipper** [comment] 2019-03-03 06:17
> string was missing the locale filter in the template, pushed a fix in [848b05b](https://github.com/peeringdb/peeringdb/commit/848b05b8e3a0b144e0006463ab306cad0701806a), should be there after next rollout.

When will it make it to the [PeeringDB Translations](https://translate.peeringdb.com/), @vegu ?

**Comment by mwtr** [comment] 2019-03-08 09:05
Regarding translation into Japanese, I have changed some translation words on https://translate.peeringdb.com/ some days ago, but they aren't reflected to production PeeringDB page... I don't know how to change translation word correctly via https://translate.peeringdb.com/ ...

**Comment by grizz** [comment] 2019-03-08 09:23
@arnoldnipper should be there now

@mwtr I just sync it to https://beta.peeringdb.com/, can you confirm?

What do you mean by you don't know how to change it via https://translate.peeringdb.com/?

**Comment by arnoldnipper** [comment] 2019-03-08 09:24
@mwtr I have escalated

**Comment by arnoldnipper** [comment] 2019-03-08 09:30
> @arnoldnipper should be there now

@grizz I'm still missing the new to be translated strings

**Comment by grizz** [comment] 2019-03-08 09:38
@arnoldnipper ok, will have to look into it more later

**Comment by arnoldnipper** [comment] 2019-04-17 12:51
@mwtr all the new strings have been loaded into https://translate.peeringdb.com. Please translate them.

**Comment by mwtr** [comment] 2019-04-18 10:28
Thank you for information, Arnold-san.

**Comment by mwtr** [comment] 2019-05-13 03:56
Hello PeeringDB administrators
When will translated strings on the PeeringDB Weblate page be introduced to the PeeringDB website?

**Comment by grizz** [comment] 2019-05-13 04:16
If you have changes, we can push them to beta to review.

**Comment by mwtr** [comment] 2019-05-13 04:22
Thank you for your responding. Could you please push current Japanese words on the Weblate page to beta PeeringDB site?

**Comment by grizz** [comment] 2019-05-13 05:05
@mwtr should be there, does it look correct?

**Comment by grizz** [comment] 2019-05-13 05:05
@arnoldnipper I think this ticket should be closed, we can do new ones as things come up, what do you think?

**Comment by mwtr** [comment] 2019-05-13 05:14
@grizz  I have checked. But it seems that new translated Japanese words aren't put to beta PeeringDB page. For example "The Interconnection Database" on the top page isn't changed into Japanese word.

https://translate.peeringdb.com/translate/peeringdb/server/ja/?checksum=&offset=&q=The+Interconnection+Database&search=regex&source=on&target=on&context=on&type=all&ignored=False&date=&only_user=&exclude_user=

**Comment by grizz** [comment] 2019-05-13 05:52
@mwtr https://github.com/peeringdb/peeringdb/issues/498

**Closed** 2019-05-13 11:28 UTC
Labels: Operations, data quality, enhancement, question, usability
