### ISSUE TITLE
When adding a facility, add drop down for "local ASN"

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#168] opened 2017-05-25 08:47 UTC
Make behaviour for IXP and Facility the same. Organsitiosn with multiples ASN should be able to chose "local ASN" like they are with IXP.

This leads to a more general question whether the relation is at the right place. I.e. it might be better to have IXP and facility where the Organization is and not where the network is.

**Comment by eloos** [comment] 2017-06-27 19:41
I think the user should add the facility to the network object that it belongs to. In my view the local_asn on the IXP should in fact be removed.
discuss...

**Comment by arnoldnipper** [comment] 2017-06-27 22:01
The way how this whole thing is implemented is broken imho. The "primary ASN" concept of PDB1.0 was simply copied to PDB2.0 However PDB2.0 does not have this concept anymore. Instead the view of IXP and Facility should be moved to Organisation. From there it makes sense to chose local_asn both for an IXP as well as for a Facility

**Comment by eloos** [comment] 2017-11-22 20:11
@arnoldnipper so this change would also impact the API functionality?
We have in fact two issues here? (a) whether we add local_asn to facilities (b) whether we move IXP/FAC directly under org.
On (a) when implementing (b) you would see facilities duplicated for every ASN that the org has?
On (b) I am not such a fan, today you have a hierarchy that spans from corporate unit (org) to administrative unit (net) to the actual peering and I think that makes sense. 
The permissions allow different parts of the corporate entity to control their part of the administrative domain.
How do we move on this?

**Comment by arnoldnipper** [comment] 2017-11-22 21:12
@eloos , how information is *displayed* is imho orthogonal to how permissions are granted. Today we have a clear asymmetry between IXP and facilities whereas from a pov of peering (ASN) there is none.

**Comment by arnoldnipper** [comment] 2017-12-10 16:09
@eloos 

> On (a) when implementing (b) you would see facilities duplicated for every ASN that the org has?
>

you already do today. If you have several ASn, you may have an entry for each ASN at the facility. Which also makes sense.

> On (b) I am not such a fan, today you have a hierarchy that spans from corporate unit (org) to
> administrative unit (net) to the actual peering and I think that makes sense.

The hierarchy is still there. You only would display the information differently.

**Comment by grizz** [comment] 2017-12-16 05:55
This is a dupe of #111 -- `local_asn` needs to die in a fire :) It would not change the API as we would just populate the `local_asn` field from the network record instead of the local table.

> The way how this whole thing is implemented is broken imho. The "primary ASN" concept of PDB1.0 was simply copied to PDB2.0 However PDB2.0 does not have this concept anymore. Instead the view of IXP and Facility should be moved to Organisation. From there it makes sense to chose local_asn both for an IXP as well as for a Facility

Agree with the former, as for the latter, all records are currently edited from their entity, which is reachable from their respective Organization. I'm against adding any functionality directly to the `org` since it would just further convolute any `net`, `fac`, `ix` tasks.

**Comment by eloos** [comment] 2017-12-16 09:27
So in summary, two decisions to take here based on the input of the ticket:
1. eliminate local_asn and keep API functionality by populating it in an API call with the network record [yes/no]
2. should the current structure with fac/ix depending on net object and not on org be maintained [yes/no]

**Comment by eloos** [comment] 2017-12-17 07:14
My choice: 1: yes, 2: yes

**Comment by arnoldnipper** [comment] 2017-12-18 17:13
Sorry @grizz  for my bad wording. I don't want to move any functionality to `org` directly. I just want to make peering at `ix` and `fac` looking symmetric. Which currently is not the case.

**Comment by kay23** [comment] 2017-12-22 13:48
My choice
* 1: yes
* 2: yes

**Comment by job** [comment] 2017-12-27 11:52
1 & 2: yes

**Comment by grizz** [comment] 2017-12-27 20:11
yes/yes

**Comment by mcmanuss8** [comment] 2018-01-04 17:11
yes/yes

**Comment by karumugham** [comment] 2018-01-05 08:23
1: yes
2: yes

**Comment by arnoldnipper** [comment] 2018-01-08 21:37
yes/yes

**Comment by fhibler** [comment] 2018-01-09 08:26
1: yes
2: yes

**Comment by nopedial** [comment] 2018-01-09 13:43
1) yes
2) yes

**Comment by thatchrisp** [comment] 2018-01-11 19:01
Yes, yes.

**Comment by arnoldnipper** [comment] 2019-02-18 14:59
> So in summary, two decisions to take here based on the input of the ticket:
> 
> 1. eliminate local_asn and keep API functionality by populating it in an API call with the network record [yes/no]
> 2. should the current structure with fac/ix depending on net object and not on org be maintained [yes/no]

1. 9 yes, 0 no
2. 9 yes, 0 no

**Comment by grizz** [comment] 2019-02-20 00:58
Thanks @arnoldnipper for picking this back up, this should be quoted.

**Closed** 2020-01-08 23:08 UTC
Labels: Quote, enhancement
