### ISSUE TITLE
[beta] IX-F importer: strange varying blank lines in IX and network emails implying possible issue

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#790] opened 2020-07-30 03:25 UTC
[I've edited the below and title, because the spec makes clear that missing IP assignments only result in an email to a network and not to the IX too.]

The email (example at https://beta.peeringdb.com/cp/peeringdb_server/ixfimportemail/?q=%5E.*seattle.*jumbo.*%24&o=5) to an IX includes wild spacing, ala:

```
-----------------------------






Data supplied by your exchange SIX Seattle (Jumbo) is in conflict with that provided by Code42 Software, Inc.. Please work with Code42 Software, Inc. to resolve this conflict or correct your data as appropriate. The Peering Admin Committee will assist with this conflict if it is not resolved in 6 days.


Your IX-F data provides IPv6 addresses for some of AS62715's peer entries, but the network has IPv6 support disabled


-----------------------------






Data supplied by your exchange SIX Seattle (Jumbo) is in conflict with that provided by Metapeer, Inc.. Please work with Metapeer, Inc. to resolve this conflict or correct your data as appropriate. The Peering Admin Committee will assist with this conflict if it is not resolved in 6 days.


Your IX-F data provides IPv6 addresses for some of AS13331's peer entries, but the network has IPv6 support disabled


-----------------------------


































Data supplied by your exchange SIX Seattle (Jumbo) is in conflict with that provided by KPU Telecom. Please work with KPU Telecom to resolve this conflict or correct your data as appropriate. The Peering Admin Committee will assist with this conflict if it is not resolved in 6 days.


MODIFY AS32204 - 206.81.83.36 - 2001:504:16:1::7dcc
- is_rs_peer: False to True

-----------------------------






Data supplied by your exchange SIX Seattle (Jumbo) is in conflict with that provided by Montana Opticom AS11924. Please work with Montana Opticom AS11924 to resolve this conflict or correct your data as appropriate. The Peering Admin Committee will assist with this conflict if it is not resolved in 6 days.


MODIFY AS11924 - 206.81.83.45 - 2001:504:16:1::2e94
- is_rs_peer: False to True

-----------------------------






Data supplied by your exchange SIX Seattle (Jumbo) is in conflict with that provided by Mountain West Technologies. Please work with Mountain West Technologies to resolve this conflict or correct your data as appropriate. The Peering Admin Committee will assist with this conflict if it is not resolved in 6 days.


MODIFY AS10947 - 206.81.83.211 - 2001:504:16:1::2ac3
- is_rs_peer: False to True

-----------------------------
```

I am concerned the wild line spacing is indicative of missed data.

**Comment by ccaputo** [comment] 2020-07-30 03:49
The spacing is also inconsistent in a network email containing multiple IXPs, ex: https://beta.peeringdb.com/cp/peeringdb_server/ixfimportemail/?q=viasat

```
This email details 2 new data mismatch[es] discovered by the PeeringDB IX-F Importer.  Please review and correct these mismatches at your PeeringDB network page (https://beta.peeringdb.com//asn/7155) or work with the indicated IXPs to correct the data.

-----------------------------




Data supplied by your network ViaSat is in conflict with that provided by SIX Seattle. Please work with SIX Seattle to resolve this conflict or correct your data at https://beta.peeringdb.com//asn/7155 as appropriate. Your network page will contain hints to assist with this. The Peering Admin Committee will assist with this conflict if it is not resolved in 6 days.


MODIFY AS7155 - 206.81.81.104 - 2001:504:16::1bf3
- speed: 42 to 100000

-----------------------------






Data supplied by your network ViaSat is in conflict with that provided by DE-CIX New York. Please work with DE-CIX New York to resolve this conflict or correct your data at https://beta.peeringdb.com//asn/7155 as appropriate. Your network page will contain hints to assist with this. The Peering Admin Committee will assist with this conflict if it is not resolved in 6 days.


MODIFY AS7155 - 206.82.105.19 - 2001:504:36::1bf3:0:1
- is_rs_peer: False to True

-----------------------------
```

On the upside, I've now confirmed the consolidation of multi-IX issue notification to a single network, per https://github.com/peeringdb/peeringdb/issues/772#issuecomment-662564888, which is great!

**Comment by vegu** [comment] 2020-07-30 10:02
This is caused by the notification template being messy when removing messages from the notifications.

The extra white-space here is left behind from the removal of "CREATE" proposals from notifications to the exchange when the network is not yet  present at the exchange.

**Comment by vegu** [comment] 2020-07-30 10:02
The messy white-space is a clear/valid bug regardless, so moving this to Ready for implementation

**Closed** 2020-08-03 19:51 UTC
Labels: bug

**Comment by ccaputo** [comment] 2020-08-11 16:18
Fix confirmed.
