### ISSUE TITLE
limit iir_as_set to a single string

### ISSUE THREAD

**Issue by as44980** [peeringdb/peeringdb#314] opened 2018-05-29 19:06 UTC
As discussed in #151 the vast majority of network records have only a single string in the iir_as_set field, so there is consideration that in addition to the syntactical validation there is value in restricting this to a single string to assist with automation..  

ie removing the need to guess if the first of these strings is the most appropriate one to use

Of the networks with more than a single string, there are only a handful with 3+ syntactically valid as-set or rs-sets.. 

And of the 90 which contain exactly two valid as-set/rs-set, ~79 of these can be inferred to represent a different routing policy for IPv6.

So if the consensous is that its would be useful to retain the capability to reflect this on a _per-network_ basis then I would propose we add a second field for iir_as_set_v6 to accommodate this use case while allowing the existing iir_as_set to be limited to a single valid as-set/rs-set.

**Comment by arnoldnipper** [comment] 2018-05-29 22:02
This is imho a duplicate of another issue where we discuss the meaning of the IRR record

**Comment by as44980** [comment] 2018-05-30 09:29
#201 seems to be a placeholder for other vauge ideas AS-SET without any real scope, so hopefully having an issue with a clear ask will encourage relevant discussion...

Speaking of which, does anyone thing that limiting iir_as_set to a single (valid) string is a bad idea?

**Comment by arnoldnipper** [comment] 2018-05-30 21:42
On 30.05.2018 11:29, as44980 wrote:

> Speaking of which, does anyone thing that limiting iir_as_set to a
> single (valid) string is a bad idea?
> 

Not bad per se ... but there might better ideas how to use this record.
Adding @4 and @6 e.g. would enhance the meaning as already does $IRR::

**Comment by as44980** [comment] 2020-07-17 00:29
> This is imho a duplicate of another issue where we discuss the meaning of the IRR record, see #201 ... would make sense to link this to it imho

As #151 and #201 have now been closed, and discussion spilled into #605, does the implementation of #151 with as-set parsing rules that include "multiple values must be separated by.." have any relevance to this specific request? :)

**Comment by as44980** [comment] 2020-10-12 09:22
Given that there was "no consensus" for any of the attempts to address the challenges faced when trying to parse multiple values in a networks "iir_as_set" field (#315 and #605), I wondered what the current thinking is on limiting this to a single string is?

Is this yet another case of deciding against improvements because "status quo works for almost everyone" and that when a network lists multiple values then "different out-of-band mechanism to discover what AS-SET should be used"?

**Comment by mahtin** [comment] 2020-11-10 16:52
I've been thinking about the `@4` and `@6` above. Then I realized we have specific data syntax for v4 and v6 addresses for IX nets; hence I would recommend we consider admitting that having a v4 and v6 value is a good way to go. Just my 2cents.

**Comment by arnoldnipper** [comment] 2020-12-06 06:37
@as44980, this issue addresses several, orthogonal problems. So, what do you want to address?

To have separate iir_as_set for IPv4 and IPv6? Or really $subject.  $subject does not really make sense to me. For two reasons. First, strictly spoken all values of `iir_as_set`are a single string. They may not be a single AS-SET/RS-SET. What would be the advantage to have that?

And for the issue to have iir_as_set and iir_as_set6 it already was decided to not implement this.

**Closed by arnoldnipper** 2020-12-06 06:37 UTC
