### ISSUE TITLE
Use autocomplete fields in the admincom controlpanel to speed up loading times

### ISSUE THREAD

**Issue by vegu** [peeringdb/peeringdb#597] opened 2019-11-07 09:14 UTC
This ticket is for the control panel UI used by admincom, **not** the customer facing UI.

Basically any page in the admin control panel that loads dropdowns with thousands of objects (networks, organizations) in them etc. is currently loading abysmally slow. Switching those dropdowns to autocomplete dropdowns will dramatically increase loading time on those pages.

We already use grappelli which comes with an autocomplete feature out of the box - so setting that up is mostly a matter of going through all the admin views and doing so.

As an added benefit, having those fields be autocomplete fields will also improve usability as dealing with lists of 16000 objects isn't really ideal.

**Comment by shane-kerr** [comment] 2019-11-07 10:23
+1 having a dropdown with more than a dozen element or so usually ends up with me typing the first letter of the choice I want anyway (for example selecting a country).

**Comment by mcmanuss8** [comment] 2019-11-07 15:24
@vegu I think it depends on the cause of the slowness. Is it getting all the possible values from the server and passing them to the client? Or does getting the full list happen quickly, and the client finding the correct value in the dropdown is the slow part?

If it's the former, I think we would want a type ahead that pushes the search term and the server returns a subset of the objects that match the search string (case insensitively, anywhere in the name). 
If it's the latter, slapping [Chosen](https://harvesthq.github.io/chosen/) or [Select2](https://select2.org/getting-started/basic-usage) on top will probably suffice.

Either way +1 we should do something here - the # of possible values has got to be way too big to select by scrolling through a dropdown.

**Comment by vegu** [comment] 2019-11-07 16:05
@mcmanuss8 I meant the former, so actual page load time - basically any relationship `<select>` gets filled with all possible entries. So for types that have a lot of objects (such as `network` or `organization`) each individual dropdown on a page currently significantly impacts loading time.

As i mentioned we already have grappelli installed which is an enhancement add-on that aims to improve the default django admin UI. It comes with an autocomplete feature that can be turned on for such fields and behaves as you described in your suggestion.

**Comment by mcmanuss8** [comment] 2019-11-07 16:18
Great, just wanted to make sure we understood the bottleneck :)

**Comment by arnoldnipper** [comment] 2019-11-07 16:45
+1 ... that would be a big help for AC

@koalafil , please go ahead. @shane-kerr @mcmanuss8 and @arnoldnipper support this issue

**Comment by grizz** [comment] 2019-11-07 17:36
+1 -- Not that we need a 4th :)

**Comment by arnoldnipper** [comment] 2020-02-24 18:33
> Basically any page in the admin control panel that loads dropdowns with thousands of objects (networks, organizations) in them etc. is currently loading abysmally slow. Switching those dropdowns to autocomplete dropdowns will dramatically increase loading time on those pages.

Very much like the new feature and would like to have it everywhere where we have tons of choices. See snapshot
![Screenshot 2020-02-24 19 30 37](https://user-images.githubusercontent.com/16888757/75180468-90f74580-573c-11ea-9e51-9d625fcc529e.png)
 attached.

**Comment by mcmanuss8** [comment] 2020-02-24 20:09
Closing this in favor of #651

**Comment by arnoldnipper** [comment] 2020-02-25 21:01
> Closing this in favor of #651

This definitely is a different issue

**Comment by koalafil** [comment] 2020-04-10 15:46
Closed in favor of https://github.com/peeringdb/peeringdb/issues/667

**Closed by koalafil** 2020-04-10 15:46 UTC
Labels: AC, Minor, Support, bug, enhancement
