### ISSUE TITLE
Search Bar does not appear upon page load

### ISSUE THREAD

**Issue by kate66** [peeringdb/peeringdb#1519] opened 2024-01-25 15:01 UTC
1. Load a PeeringDB page (Ex: https://www.peeringdb.com/net/4549) on your desktop browser.
2. Notice that search bar is collapsed for mobile view and requires a click on the icon prior to expanding.

**Comment by eb0815** [comment] 2024-01-26 11:22
Actually, it's the same change on desktop browsers. Worst of it, even when you click on the icon, input isn't focused on the input field, you have to goddamn click again. This is really really bad design and a change that needs to be reverted right away.

**Comment by benjojo** [comment] 2024-01-26 15:11
Dupe of https://github.com/peeringdb/peeringdb/issues/1511

**Comment by leovegoda** [comment] 2024-01-31 16:06
Addressed in https://github.com/peeringdb/peeringdb/pull/1529

**Closed by leovegoda** 2024-01-31 16:06 UTC
