### ISSUE TITLE
renumbering tool is not renumbering all IPs, though in the given range

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#293] opened 2018-03-01 23:54 UTC
Pls see https://peeringdb.com/cp/peeringdb_server/commandlinetool/1/change/ and https://peeringdb.com/ix/491
![20180302 peeringdb 00](https://user-images.githubusercontent.com/16888757/36876215-2cfdbf82-1db4-11e8-9837-419d1f27f774.png)

**Comment by arnoldnipper** [comment] 2018-03-02 00:03
Hmmm ... this also could have been pebcak :) ... May I propose to change the command to include a **mask**, eg Old: 195.191.171.0/23, New: 178.216.40.0/23

**Comment by vegu** [comment] 2018-03-02 05:37
To make sure i attempted to reproduce in our dev environment, and seemed to work correctly (same ix, same number change).

However there were a few netixlans that could not be renumbered because their ip addresses already existed elsewhere, currently those are noted in the command output log with an "`[error]`" prefix and they are kept as is because the command is not smart enough to know what to do with those at this point. 

No idea if that contributed to what you were seeing.

**Comment by arnoldnipper** [comment] 2018-03-02 19:55
@vegu, if you want to renumber a /23 you have to run the tool for each /24. Right? Hence my feature request of being able to add a mask.

**Comment by grizz** [comment] 2020-03-06 20:52
Closing, this was from the old version of the tool.

**Closed by grizz** 2020-03-06 20:52 UTC
Labels: AC, bug
