### ISSUE TITLE
Admin UI is slow

### ISSUE THREAD

**Issue by job** [peeringdb/peeringdb#93] opened 2016-12-07 22:57 UTC
A number of actions in the `/cp` interface is very slow:

- Adding a network
- affiliating a user
- adding an organisation
- adding a facility
- adding an IXP
- merging organisations is super slow while you lookup orgs

I have a suspicion that this is because all possible items are loaded in the DOM, providing the PDB Administrator with a complete overview, but a slow browsing experience. 10,000+ items in a pull down menu is not ideal from a UI perspective.

On the server side there might also be a slowdown in rendering the template for 10k items.

Any help would be greatly appreciated, the slowness is impacting the work of Admins and making their life miserable. It'll be more enjoyable to do tickets if the UI is fast as fuck.

**Comment by vegu** [comment] 2016-12-08 09:11
There appears to be a bug with the listings being slow - which would also affect adding new objects, as that action goes back to the listing after it is completed. Looks like the culprit was an outdated library and updating seems to have fixed it, internetexchange listing went from a 10 second load to < 1 seconds. Can review further once its rolled to beta.

fixed in 8ddc8b3

**Comment by job** [comment] 2016-12-08 10:36
@vegu wowzers! That is the best thing i've read this morning. :-)

What is the ETA on putting up a beta?

**Comment by arnoldnipper** [comment] 2016-12-22 19:44
I don't see real improvement. All type of actions may still take up to 10s or more

**Comment by vegu** [comment] 2016-12-22 20:11
strange, i dont see any slow performance on my end after the update, might be something more occasional with server load.

**Comment by vegu** [comment] 2016-12-22 20:15
how easy is this for you to reproduce, is it pretty much all the time but only on the admin ui interface? if not all the time, when do you usually see this?

**Comment by arnoldnipper** [comment] 2016-12-23 09:24
Very easy to reproduce when using the admin GUI

**Comment by arnoldnipper** [comment] 2016-12-23 09:25
Especially https://peeringdb.com/cp/peeringdb_server/organization/org-merge-tool/ needs a redesign

**Comment by vegu** [comment] 2016-12-23 09:54
organization merge tool appears to be performing much worse in chrome than it does in firefox or safari, that's something that we will need to look at for sure, are you on chrome ?

Alas outside of the org-merge tool, i still have had no luck reproducing what you are seeing (on the dev environment). I assume "all kinds of actions" refers to saves? or do you get the slowness on list loads still as well?

**Comment by arnoldnipper** [comment] 2016-12-23 14:43
Yes, on chrome .... when saving ans looking up as well

**Comment by vegu** [comment] 2017-02-03 09:04
Do you see the same performance issues on beta.peeringdb.com ?

**Comment by arnoldnipper** [comment] 2017-02-03 14:21
Not the same, but similiar. And it is hard to compare. Especially as it's not possibel to be logged in in beta.peeringdb.com and peeringdb.com at the same time. If I log in to one I get logged out at the other

**Comment by job** [comment] 2017-02-03 14:28
@arnoldnipper you can log in at the same time just open beta.peeringdb.com in a "private browsing window" (on macosx with chrome: shift-cmd-n to open such a window)

**Comment by vegu** [comment] 2017-03-08 07:24
still unable to reproduce for the most part,  i did however manage to find one instance (outside of the org merge tool) where i get the same response times you do.

Here is what i tried on prod, did not want to dirty the db so what i could try here is limited

- save change to existing org (1-3 seconds)
- lookup asn (1-2 seconds)

Here is what i tried on beta

- load admin UI for ASN 15169 (id:433) (6 seconds)
- save change to ASN 15169 (id:433) (6-12 seconds)
- save new org (< 1 second)
- save existing org (< 1 second)
- lookup asn (1-2 seconds)

> load admin UI for ASN 15169 (id:433) (6 seconds)
> save change to ASN 15169 (id:433) (6-12 seconds)

The culprit here appears to be how Django admin UI handles saves to objects that have many children, in this case the ASN has loads of netixlans and netfacs under it (100+ forms), which both cause Django  Admin UI load times and save times to deteriorate.

The most obvious fix for this would be to take netixlans and netfacs lists out of the network Admin UI and have separate views for them. It comes down to what is less inconvenient for you guys at this point. 

Since this would only affect those objects with lots of children already under them, for now you could also resort to making changes to those using the public pdb UI instead.

I am still not able to reproduce slowness outside of this, so if you see it elsewhere can you please state the action (save org X for example), time (UTC) and how long it took, it will help pin point the cause.

**Comment by grizz** [comment] 2017-07-06 16:45
@arnoldnipper @job we are unable to reproduce this and no one has responded, what do you expect us to do?

**Comment by arnoldnipper** [comment] 2017-07-06 18:53
To make it fast ... which ewnvironments did you test? E.g. https://peeringdb.com/cp/peeringdb_server/organization/org-merge-tool/ is super, super, super slow and unresponsive.

Happy to share a session

**Comment by grizz** [comment] 2017-07-06 19:27
There is a full post about this 2 comments above

**Comment by arnoldnipper** [comment] 2017-07-06 20:01
vegu / grizz.

> I am still not able to reproduce slowness outside of this, so if you see it elsewhere can you please state > the action (save org X for example), time (UTC) and how long it took, it will help pin point the cause.

is not really a useful hint as I do not always count how long the action took. Any change to add this info to the GUI.

And believe me. Performance is far from what I expect

**Comment by vegu** [comment] 2017-07-07 15:22
Duration doesn't really matter that much to track it down (just thought it would be interesting to have), just name of action and a timestamp would be sufficient.

> The culprit here appears to be how Django admin UI handles saves to objects that have many children, in this case the ASN has loads of netixlans and netfacs under it (100+ forms), which cause Django Admin UI load times and save times to deteriorate

> The most obvious fix for this would be to take netixlans and netfacs lists out of the network Admin UI and have separate views for them. It comes down to what is less inconvenient for you guys at this point.

Any input on this?

**On a related note**, since the org merge tool has been brought up multiple times: 

As i mentioned a while back the org merge tool needs to be refactored, let's make a separate ticket for that, as there is definitely something wrong within it that's making it slow, however i would consider it unrelated to the general admin ui slowness we are witnessing.

I created a separate ticket here:  #183

**Closed** 2018-03-11 23:57 UTC
Labels: AC, bug
