### ISSUE TITLE
Sync uses local time rather than UTC which causes problems with people West of UTC

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#721] opened 2020-05-15 22:50 UTC
[issue](https://github.com/peeringdb/peeringdb-py/issues/36) from [peeringdb-py](https://github.com/peeringdb/peeringdb-py/issues). Should be fixed asap according to @ccaputo

**Comment by mngan** [comment] 2020-05-16 01:06
I replicated the problem and added some additional debugging to illustrate the problem. The first time stamp is what is in the object and is in UTC, the second is the UTC timestamp for now, and the third is the local timestamp. You can see that the update time is in the "future" by about 37 minutes from the local time, but is about 7 hours old when compared to UTC. 

``` 
Syncing to https://www.peeringdb.com/api
Updating resources: org fac net ix ixfac ixlan ixpfx netfac netixlan poc
Fetching & updating all: org
Updates to be processed: 10
Ignoring object updated after sync began: (org-26096)
UPDATED: 2020-05-15 14:59:14, UTC: 2020-05-15 21:22:31.806911, NOW: 2020-05-15 14:22:31.806908
Ignoring object updated after sync began: (org-26092)
UPDATED: 2020-05-15 15:29:39, UTC: 2020-05-15 21:22:31.806911, NOW: 2020-05-15 14:22:31.806908
Ignoring object updated after sync began: (org-26097)
UPDATED: 2020-05-15 15:55:02, UTC: 2020-05-15 21:22:31.806911, NOW: 2020-05-15 14:22:31.806908
Ignoring object updated after sync began: (org-26094)
```

I think the problem is that because the code filters out objects that have "changed" after the sync time. However even if those objects existed prior to that time they may not get inserted, thus causing referential integrity issues. I think the intent was that in the worst case you would be some amount of time behind PeeringDB, but this is not the case. I think the logic that is there is pretty dangerous because within the window of you performing the sync, you might hit this case, but it is pretty rare since a full sync probably takes 3-4 minutes and an incremental less than a minute. 

1. Object A gets created at time X and is referenced by Object B
2. Start sync at time X+1
3. Object A gets updated at X+2
4. Try to sync object A at X+3 but is skipped leaving Object B with a dangling reference to Object A 

Now in combination with the timezone issue, the window where you can get inconsistent changes is like 7/8 hours for people here in on the West Coast of the US. A lot of changes can happen in 7/8 hours...

**Comment by arnoldnipper** [comment] 2020-09-18 22:12
Same as #786

**Comment by mngan** [comment] 2020-09-19 00:11
It looks like this was committed into the 1.1.0 release, which was released in August.

**Comment by arnoldnipper** [comment] 2020-09-25 20:20
@mngan if it is fixed, please close the issue

**Comment by mngan** [comment] 2020-09-25 21:47
I don't think I have the ability to do that, or am I just missing something in the UI? I can only post comments as far as I can tell.

**Closed** 2020-09-25 22:08 UTC
Labels: bug
