### ISSUE TITLE
[prod] IX-F importer: NameError: name 'EmailMultiAlternatives' is not defined

### ISSUE THREAD

**Issue by ccaputo** [peeringdb/peeringdb#831] opened 2020-08-26 21:23 UTC
First attempt to send email resulted in the following:

```
$ time flock -x -w 240 /tmp/pdb_ixf_ixp_import.lock /home/pdb/bin/pdb-container pdb_ixf_ixp_member_import --commit --ixlan 1285 --asn 6456
Fetching data for -ixlan1285 from https://www.seattleix.net/autogen/participants.json
Processing SIX Seattle (Jumbo) (1285)
Success: True, added: 0, updated: 0, deleted: 0
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/www.peeringdb.com/venv/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/www.peeringdb.com/peeringdb_server/management/commands/pdb_ixf_ixp_member_import.py", line 252, in handle
    importer.notify_proposals()
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1498, in notify_proposals
    self._email(subject, message, contacts, ix=data["entity"])
  File "/srv/www.peeringdb.com/peeringdb_server/ixf.py", line 1221, in _email
    mail = EmailMultiAlternatives(
NameError: name 'EmailMultiAlternatives' is not defined

real    0m3.531s
user    0m0.023s
sys     0m0.033s
```

Immediate retry afterward failed to retry the email:

```
$ time flock -x -w 240 /tmp/pdb_ixf_ixp_import.lock /home/pdb/bin/pdb-container pdb_ixf_ixp_member_import --commit --ixlan 1285 --asn 6456
Fetching data for -ixlan1285 from https://www.seattleix.net/autogen/participants.json
Processing SIX Seattle (Jumbo) (1285)
Success: True, added: 0, updated: 0, deleted: 0
Emails: 0

real    0m3.644s
user    0m0.034s
sys     0m0.031s
```

So two issues: 1) Email is not working.  2) When email fails, the rest of the commit succeeds such that a retry to send the email does not work.

**Comment by ccaputo** [comment] 2020-08-26 21:52
To be clear about #2, I think it should be like a database transaction.  An email does not get logged in the table unless actually sent, rather an email failure should be logged.  And when a subsequent attempt succeeds, the email should then be logged.

**Comment by egfrank** [comment] 2020-08-26 23:39
At the moment it seems like we are creating an email in the table first, and after it successfully gets sent it is re-saved with a `sent` timestamp. So the email in question should have an entry in the log table (created from the first attempt) with `sent == null`, thereby signaling it was a failure. 

It seems like, currently, if the email is retried successfully, we are creating a new (successful) log entry. I agree it makes sense that we should instead be looking up if there was a failed attempt, and adding the `sent` field when it gets sent successfully.

**Comment by ccaputo** [comment] 2020-08-26 23:44
> At the moment it seems like we are creating an email in the table first, and after it successfully gets sent it is re-saved with a `sent` timestamp. So the email in question should have an entry in the log table (created from the first attempt) with `sent == null`, thereby signaling it was a failure.

Confirmed that this is the case: Sent is null.

> It seems like, currently, if the email is retried successfully, we are creating a new (successful) log entry.

From what I can tell, the email is not retried.

> I agree it makes sense that we should instead be looking up if there was a failed attempt, and adding the `sent` field when it gets sent successfully.

I don't think so.   The failures need to remain logged and not replaced, so that there is a trail for later analysis.

**Comment by egfrank** [comment] 2020-08-26 23:58
| It seems like, currently, if the email is retried successfully, we are creating a new (successful) log entry.
Sorry this was unclear. I meant if the user re-runs the email sending manually. I'm assuming here that the email sending would usually (ie once we push a fix for this bug) fail temporarily because of a connection issue or something.

| I don't think so. The failures need to remain logged and not replaced, so that there is a trail for later analysis.
Oh great, I misunderstood what you were saying. Then it seems like currently we are doing what you suggest, logging a failure (`sent==null`)  and then if the email is successful the next time it is attempted, a new log with `sent==current_timestamp` will be created.

**Comment by egfrank** [comment] 2020-08-27 16:29
Hi Chris! Just checking up on this, after talking with @vegu we've confirmed the two bugs you identified originally, and are going to be split those into two issues:

1) We've developed a fix for the email not working because of the import error bug, and that can go into production without being on beta

2) I've confirmed that, like you stated, if a commit succeeds but the email fails, there is currently no mechanism to re-send that email on a second run. The logic to send an email is entirely dependent on notifications from the import process, and if the importer is re-run on the same data, no new notifications are produced. To fix this bug, we need to implement email resending in the importer, which will require some speccing out and time on beta.

**Comment by ccaputo** [comment] 2020-08-27 16:45
> 2. I've confirmed that, like you stated, if a commit succeeds but the email fails, there is currently no mechanism to re-send that email on a second run. The logic to send an email is entirely dependent on notifications from the import process, and if the importer is re-run on the same data, no new notifications are produced. To fix this bug, we need to implement email resending in the importer, which will require some speccing out and time on beta.

I wonder it if makes sense to simply not commit to `ixfmemberdata` or other involved non-email tables when an email fails?  That way, next time importer runs, it is a clean slate and the issue will be rediscovered.  Ie.:

  - create email in table for network (as appropriate) with sent == null
  - create email in table for ix (as appropriate) with sent == null
  - attempt to send network email and set `sent` if successful
  - attempt to send ix email and set `sent` if successful
  - if emails successful, commit changes to `ixfmemberdata` and any other involved tables

**Comment by egfrank** [comment] 2020-08-27 16:53
Btw Chris I just split this issue off to 
https://github.com/peeringdb/peeringdb/issues/833, sorry I didn't finish writing it before you commented!

**Closed** 2020-09-29 18:07 UTC
Labels: bug

**Comment by ccaputo** [comment] 2020-10-07 21:31
I have confirmed that production release 2.23.0 of the Importer is now able to send emails.
