### ISSUE TITLE
Get "rir_status: This field cannot be blank." sorted out when reverting changes

### ISSUE THREAD

**Issue by arnoldnipper** [peeringdb/peeringdb#1248] opened 2022-09-19 14:52 UTC
**Describe the bug**
When reverting changes, I now run into the error "rir_status: This field cannot be blank." every now and then. IMO this is a bug

**To Reproduce**
1. Go to https://www.peeringdb.com/cp/peeringdb_server/network/30989/history/?_changelist_filters=q%3D150046
2. Click on "Revert changes"
3. See error

**Expected behavior**
Ignore field `rir_status` or set to `null`

**Who is affected by the problem?**
@peeringdb/ac, please confirm

**Comment by martinhannigan** [comment] 2022-09-19 15:08
What is this field for? What RIR Status?

**Comment by peterhelmenstine** [comment] 2022-09-20 00:19
I'm sorry. I'm not able to reproduce...

**Comment by leovegoda** [comment] 2022-09-29 16:33
Has this been reproduced since the initial report?

**Comment by leovegoda** [comment] 2023-09-20 15:57
Has this ever been reproduced? If not, could we close it?

**Comment by leovegoda** [comment] 2023-11-15 18:20
@peeringdb/ac Has this ever been reproduced? If not, it would be good to close.

**Comment by arnoldnipper** [comment] 2023-11-17 08:23
Look at ASN

919
4280
7607
8338
9434
9833
11611
13752
15238
17193
21042
22497
22698
24735
24931
26067
26795
28152
28364
32457
33531
35156
35305
35799
39070
39925
41792
45737
45816
47149
47298
47529
49541
49547
49565
50622
51501
52302
52690
52902
53082
53149
53397
55480
56103
57436
60428
60546
61004
61130
61833
62355
131108
132087
132316
132894
134156
134171
134602
136467
136607
136745
137871
139058
139833
139880
139921
140219
141007
141677
141749
142030
142044
142148
142165
142294
142570
149296
149506
149510
198741
198908
199592
201379
201445
201613
201801
202019
202437
203113
203146
204610
204613
204840
205079
205271
205942
206033
208196
208445
209870
211265
211352
211459
211489
211602
211692
213282
262327
262330
262336
262730
262745
262748
262819
262983
263314
263542
264006
264026
264282
264478
264538
265414
266350
266587
266896
266991
267223
267276
267615
267631
267639
268090
268225
268495
268561
268666
268767
269019
269071
269161
269313
270284
270345
270774
270898
271123
271449
328416
329360
394837
394894
395822
398418
398951
399382
399389
399497
400647

**Comment by grizz** [comment] 2024-08-01 15:54
Unable to reproduce, tried a couple of them on beta -- guessing it was already fixed.

**Closed by grizz** 2024-08-01 15:54 UTC
Labels: bug, AC
